/**
*   @file    Sema_Reg.h
*   @version 1.5.1
*
*   @brief   AUTOSAR Sema - module register and macro definitions.
*   @details Sema module registers, and macrodefinitions used to manipulate the module registers.
*
*   @addtogroup Common
*   @{
*/
/*==================================================================================================
*   PERIPHERAL           : Mailbox
*   PLATFORM             : Flagchip FC7300
*   AUTOSAR VERSION      : 4.6.0
*   AUTOSAR REVISION     : ASR_REL_4_6_0
*   SOFTWARE VERSION     : 1.5.1
*   VENDOR               : Flagchip Semiconductors
*
*   Copyright 2020-2023 Flagchip Semiconductors Co., Ltd.
*   All Rights Reserved.
==================================================================================================*/
/*==================================================================================================
*   Revision History:
*
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------- ----------   ---------------
*   0.9.0       25/10/2024    QXW0070       N/A          SEMA Initial Version
==================================================================================================*/
#ifndef SEMA_REGS_H_
#define SEMA_REGS_H_
#ifdef __cplusplus
extern "C" {
#endif

#include "Std_Types.h"

/** SEMA - Size of Registers Arrays */
#define SEMA_STATUS_COUNT 	16
#define SEMA_RSRC_COUNT 	256

/** SEMA - Register Layout Typedef */
typedef struct {
	__IO uint32 SEMAn_STATUS[SEMA_STATUS_COUNT]; /* Semaphore Status Register, offset: 0xb00 */
		 uint8  RESERVED_21[128];
	__IO uint32 SEMA_GLOBAL_STATUS            ; /* Semaphore Global Status Register, offset: 0xBC0 */
		 uint8  RESERVED_22[12];
	__IO uint32 SEMA_CTRL                     ; /* Semaphore Control Register, offset: 0xBD0 */
	__IO uint32 SEMA_ERROR_STATUS             ; /* Semaphore Error Status Register, offset: 0xBD4 */
	__IO uint32 SEMA_SW_RESET                 ; /* Semaphore Software Reset Register, offset: 0xBD8 */
		 uint8  RESERVED_23[4];
	__IO uint32 SEMA_RELEASE                  ; /* Semaphore Release Register, offset: 0xBE0 */
		 uint8  RESERVED_24[28];
	__IO uint32 SEMA_RSRC[SEMA_RSRC_COUNT] ; /* Semaphore Resource Register, offset: 0xc00 */
} SEMA_Type;

/* SEMA - Peripheral instance base addresses */

/** Peripheral SEMA base address */
#define SEMA_BASE                                  (0x40058B00u)

/** Peripheral MB base pointer */

#define SEMA                                       ((SEMA_Type *)SEMA_BASE)

/** Array initializer of SEMA peripheral base addresses */

#define SEMA_BASE_ADDRS                            {SEMA_BASE}

/** Array initializer of MB peripheral base pointers */

#define SEMA_BASE_PTRS                             {SEMA}

/* SEMAn_STATUS Bit Fields */
#define SEMAn_STATUS_SEMA_RSRC_ID_MASK 0xFF0u
#define SEMAn_STATUS_SEMA_RSRC_ID_SHIFT 4u
#define SEMAn_STATUS_SEMA_RSRC_ID_WIDTH 8u
#define SEMAn_STATUS_SEMA_RSRC_ID(x) (((uint32_t)(((uint32_t)(x))<<SEMAn_STATUS_SEMA_RSRC_ID_SHIFT))&SEMAn_STATUS_SEMA_RSRC_ID_MASK)
#define SEMAn_STATUS_SEMA_MID_MASK  0xEu
#define SEMAn_STATUS_SEMA_MID_SHIFT 1u
#define SEMAn_STATUS_SEMA_MID_WIDTH 3u
#define SEMAn_STATUS_SEMA_MID(x)    (((uint32_t)(((uint32_t)(x))<<SEMAn_STATUS_SEMA_MID_SHIFT))&SEMAn_STATUS_SEMA_MID_MASK)
#define SEMAn_STATUS_SEMA_FLG_MASK  0x1u
#define SEMAn_STATUS_SEMA_FLG_SHIFT 0u
#define SEMAn_STATUS_SEMA_FLG_WIDTH 1u
#define SEMAn_STATUS_SEMA_FLG(x)    (((uint32_t)(((uint32_t)(x))<<SEMAn_STATUS_SEMA_FLG_SHIFT))&SEMAn_STATUS_SEMA_FLG_MASK)
/* SEMA0_STATUS Reg Mask */
#define SEMAn_STATUS_MASK           0x00000FFFu

/* SEMA_GLOBAL_STATUS Bit Fields */
#define SEMA_GLOBAL_STATUS_SEMA15_STATUS_MASK 0x8000u
#define SEMA_GLOBAL_STATUS_SEMA15_STATUS_SHIFT 15u
#define SEMA_GLOBAL_STATUS_SEMA15_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA15_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA15_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA15_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA14_STATUS_MASK 0x4000u
#define SEMA_GLOBAL_STATUS_SEMA14_STATUS_SHIFT 14u
#define SEMA_GLOBAL_STATUS_SEMA14_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA14_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA14_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA14_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA13_STATUS_MASK 0x2000u
#define SEMA_GLOBAL_STATUS_SEMA13_STATUS_SHIFT 13u
#define SEMA_GLOBAL_STATUS_SEMA13_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA13_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA13_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA13_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA12_STATUS_MASK 0x1000u
#define SEMA_GLOBAL_STATUS_SEMA12_STATUS_SHIFT 12u
#define SEMA_GLOBAL_STATUS_SEMA12_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA12_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA12_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA12_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA11_STATUS_MASK 0x800u
#define SEMA_GLOBAL_STATUS_SEMA11_STATUS_SHIFT 11u
#define SEMA_GLOBAL_STATUS_SEMA11_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA11_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA11_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA11_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA10_STATUS_MASK 0x400u
#define SEMA_GLOBAL_STATUS_SEMA10_STATUS_SHIFT 10u
#define SEMA_GLOBAL_STATUS_SEMA10_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA10_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA10_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA10_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA9_STATUS_MASK 0x200u
#define SEMA_GLOBAL_STATUS_SEMA9_STATUS_SHIFT 9u
#define SEMA_GLOBAL_STATUS_SEMA9_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA9_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA9_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA9_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA8_STATUS_MASK 0x100u
#define SEMA_GLOBAL_STATUS_SEMA8_STATUS_SHIFT 8u
#define SEMA_GLOBAL_STATUS_SEMA8_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA8_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA8_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA8_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA7_STATUS_MASK 0x80u
#define SEMA_GLOBAL_STATUS_SEMA7_STATUS_SHIFT 7u
#define SEMA_GLOBAL_STATUS_SEMA7_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA7_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA7_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA7_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA6_STATUS_MASK 0x40u
#define SEMA_GLOBAL_STATUS_SEMA6_STATUS_SHIFT 6u
#define SEMA_GLOBAL_STATUS_SEMA6_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA6_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA6_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA6_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA5_STATUS_MASK 0x20u
#define SEMA_GLOBAL_STATUS_SEMA5_STATUS_SHIFT 5u
#define SEMA_GLOBAL_STATUS_SEMA5_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA5_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA5_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA5_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA4_STATUS_MASK 0x10u
#define SEMA_GLOBAL_STATUS_SEMA4_STATUS_SHIFT 4u
#define SEMA_GLOBAL_STATUS_SEMA4_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA4_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA4_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA4_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA3_STATUS_MASK 0x8u
#define SEMA_GLOBAL_STATUS_SEMA3_STATUS_SHIFT 3u
#define SEMA_GLOBAL_STATUS_SEMA3_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA3_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA3_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA3_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA2_STATUS_MASK 0x4u
#define SEMA_GLOBAL_STATUS_SEMA2_STATUS_SHIFT 2u
#define SEMA_GLOBAL_STATUS_SEMA2_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA2_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA2_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA2_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA1_STATUS_MASK 0x2u
#define SEMA_GLOBAL_STATUS_SEMA1_STATUS_SHIFT 1u
#define SEMA_GLOBAL_STATUS_SEMA1_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA1_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA1_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA1_STATUS_MASK)
#define SEMA_GLOBAL_STATUS_SEMA0_STATUS_MASK 0x1u
#define SEMA_GLOBAL_STATUS_SEMA0_STATUS_SHIFT 0u
#define SEMA_GLOBAL_STATUS_SEMA0_STATUS_WIDTH 1u
#define SEMA_GLOBAL_STATUS_SEMA0_STATUS(x) (((uint32_t)(((uint32_t)(x))<<SEMA_GLOBAL_STATUS_SEMA0_STATUS_SHIFT))&SEMA_GLOBAL_STATUS_SEMA0_STATUS_MASK)
/* SEMA_GLOBAL_STATUS Reg Mask */
#define SEMA_GLOBAL_STATUS_MASK     0x0000FFFFu

/* SEMA_CTRL Bit Fields */
#define SEMA_CTRL_SEMA_LOCK_CHECK_CTRL_MASK 0x1u
#define SEMA_CTRL_SEMA_LOCK_CHECK_CTRL_SHIFT 0u
#define SEMA_CTRL_SEMA_LOCK_CHECK_CTRL_WIDTH 1u
#define SEMA_CTRL_SEMA_LOCK_CHECK_CTRL(x) (((uint32_t)(((uint32_t)(x))<<SEMA_CTRL_SEMA_LOCK_CHECK_CTRL_SHIFT))&SEMA_CTRL_SEMA_LOCK_CHECK_CTRL_MASK)
/* SEMA_CTRL Reg Mask */
#define SEMA_CTRL_MASK              0x00000001u

/* SEMA_ERROR_STATUS Bit Fields */
#define SEMA_ERROR_STATUS_SEMA_ERR_RSRC_ID_MASK 0x1FE0u
#define SEMA_ERROR_STATUS_SEMA_ERR_RSRC_ID_SHIFT 5u
#define SEMA_ERROR_STATUS_SEMA_ERR_RSRC_ID_WIDTH 8u
#define SEMA_ERROR_STATUS_SEMA_ERR_RSRC_ID(x) (((uint32_t)(((uint32_t)(x))<<SEMA_ERROR_STATUS_SEMA_ERR_RSRC_ID_SHIFT))&SEMA_ERROR_STATUS_SEMA_ERR_RSRC_ID_MASK)
#define SEMA_ERROR_STATUS_SEMA_ERR_MID_MASK 0x1Cu
#define SEMA_ERROR_STATUS_SEMA_ERR_MID_SHIFT 2u
#define SEMA_ERROR_STATUS_SEMA_ERR_MID_WIDTH 3u
#define SEMA_ERROR_STATUS_SEMA_ERR_MID(x) (((uint32_t)(((uint32_t)(x))<<SEMA_ERROR_STATUS_SEMA_ERR_MID_SHIFT))&SEMA_ERROR_STATUS_SEMA_ERR_MID_MASK)
#define SEMA_ERROR_STATUS_SEMA_ERR_KEY_MASK 0x2u
#define SEMA_ERROR_STATUS_SEMA_ERR_KEY_SHIFT 1u
#define SEMA_ERROR_STATUS_SEMA_ERR_KEY_WIDTH 1u
#define SEMA_ERROR_STATUS_SEMA_ERR_KEY(x) (((uint32_t)(((uint32_t)(x))<<SEMA_ERROR_STATUS_SEMA_ERR_KEY_SHIFT))&SEMA_ERROR_STATUS_SEMA_ERR_KEY_MASK)
#define SEMA_ERROR_STATUS_SEMA_ERR_ST_MASK 0x1u
#define SEMA_ERROR_STATUS_SEMA_ERR_ST_SHIFT 0u
#define SEMA_ERROR_STATUS_SEMA_ERR_ST_WIDTH 1u
#define SEMA_ERROR_STATUS_SEMA_ERR_ST(x) (((uint32_t)(((uint32_t)(x))<<SEMA_ERROR_STATUS_SEMA_ERR_ST_SHIFT))&SEMA_ERROR_STATUS_SEMA_ERR_ST_MASK)
/* SEMA_ERROR_STATUS Reg Mask */
#define SEMA_ERROR_STATUS_MASK      0x00001FFFu

/* SEMA_SW_RESET Bit Fields */
#define SEMA_SW_RESET_SEMA_SW_RESET_CTRL_MASK 0xFFFFFFFFu
#define SEMA_SW_RESET_SEMA_SW_RESET_CTRL_SHIFT 0u
#define SEMA_SW_RESET_SEMA_SW_RESET_CTRL_WIDTH 32u
#define SEMA_SW_RESET_SEMA_SW_RESET_CTRL(x) (((uint32_t)(((uint32_t)(x))<<SEMA_SW_RESET_SEMA_SW_RESET_CTRL_SHIFT))&SEMA_SW_RESET_SEMA_SW_RESET_CTRL_MASK)
/* SEMA_SW_RESET Reg Mask */
#define SEMA_SW_RESET_MASK          0xFFFFFFFFu

/* SEMA_RELEASE Bit Fields */
#define SEMA_RELEASE_SEMA_RELEASE_CTRLL_MASK 0xFFFFFFFFu
#define SEMA_RELEASE_SEMA_RELEASE_CTRLL_SHIFT 0u
#define SEMA_RELEASE_SEMA_RELEASE_CTRLL_WIDTH 32u
#define SEMA_RELEASE_SEMA_RELEASE_CTRLL(x) (((uint32_t)(((uint32_t)(x))<<SEMA_RELEASE_SEMA_RELEASE_CTRLL_SHIFT))&SEMA_RELEASE_SEMA_RELEASE_CTRLL_MASK)
/* SEMA_RELEASE Reg Mask */
#define SEMA_RELEASE_MASK           0xFFFFFFFFu

/* SEMA_RSRC Bit Fields */
#define SEMA_RSRC_SEMA_RSRC_ID_MASK 0xFF0u
#define SEMA_RSRC_SEMA_RSRC_ID_SHIFT 4u
#define SEMA_RSRC_SEMA_RSRC_ID_WIDTH 8u
#define SEMA_RSRC_SEMA_RSRC_ID(x)   (((uint32_t)(((uint32_t)(x))<<SEMA_RSRC_SEMA_RSRC_ID_SHIFT))&SEMA_RSRC_SEMA_RSRC_ID_MASK)
#define SEMA_RSRC_SEMA_MID_MASK     0xEu
#define SEMA_RSRC_SEMA_MID_SHIFT    1u
#define SEMA_RSRC_SEMA_MID_WIDTH    3u
#define SEMA_RSRC_SEMA_MID(x)       (((uint32_t)(((uint32_t)(x))<<SEMA_RSRC_SEMA_MID_SHIFT))&SEMA_RSRC_SEMA_MID_MASK)
#define SEMA_RSRC_SEMA_FLG_MASK     0x1u
#define SEMA_RSRC_SEMA_FLG_SHIFT    0u
#define SEMA_RSRC_SEMA_FLG_WIDTH    1u
#define SEMA_RSRC_SEMA_FLG(x)       (((uint32_t)(((uint32_t)(x))<<SEMA_RSRC_SEMA_FLG_SHIFT))&SEMA_RSRC_SEMA_FLG_MASK)
/* SEMA_RSRC0 Reg Mask */
#define SEMA_RSRC_MASK              0x00000FFFu

/** SEMA Keys */
#define SEMA_KEY_UNLOCK             	0xFCA05F00u
#define SEMA_KEY_RELEASE            	0xFC50A05Fu
#define SEMA_KEY_CLEAR_ERROR        	0xA05FFC00u
#define SEMA_KEY_SW_RESET           	0xA05F50FCu
#define SEMA_KEY_RELEASE_ALL			0xFC500000u

#ifdef __cplusplus
}
#endif
#endif

/** @} */
