/**
*   @file    CDD_Sdadc_Cfg.h
*   @version 1.5.1
*
*   @brief   AUTOSAR SDADC - hardware specific type definition
*   @details This file contains the SDADC AUTOSAR hardware specific type definition
*
*   @addtogroup SDADC
*   @{
*/
/*==================================================================================================
*   PERIPHERAL           : Sdadc
*   PLATFORM             : Flagchip FC7300
*   AUTOSAR VERSION      : 4.6.0
*   AUTOSAR REVISION     : ASR_REL_4_6_0
*   SOFTWARE VERSION     : 1.5.1
*   VENDOR               : Flagchip Semiconductors
*
*   Copyright 2020-2024 Flagchip Semiconductors Co., Ltd.
*   All Rights Reserved.
==================================================================================================*/
/*==================================================================================================
*   Revision History:
*
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------- ----------   ---------------
*   0.8.0       20/8/2024     QXW0084       N/A          SDADC Initial Version
==================================================================================================*/
#ifndef SDADC_CFG_H
#define SDADC_CFG_H

#ifdef __cplusplus
extern "C" {
#endif

#include "Std_Types.h"
#include "Mcal.h"

#define SDADC_GLOBAL_TS_SUPPORT (STD_OFF)
#if (STD_ON == SDADC_GLOBAL_TS_SUPPORT)
#include "CDD_Dma.h"
#endif

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
/* PRQA S 0791 ++ #Misra-C:2012 Rule-5.4 Macro identifiers shall be distinct
 * Reason: There are some marcos generated by configuration tool which used by user, so, this macros may not distinct */
#define SDADC_CFG_AR_RELEASE_MAJOR_VERSION        4U
#define SDADC_CFG_AR_RELEASE_MINOR_VERSION        6U
#define SDADC_CFG_AR_RELEASE_REVISION_VERSION     0U
#define SDADC_CFG_SW_MAJOR_VERSION                1U
#define SDADC_CFG_SW_MINOR_VERSION                5U
#define SDADC_CFG_SW_PATCH_VERSION                1U
#define SDADC_CFG_MODULE_ID                       255U
#define SDADC_CFG_VENDOR_ID                       174U

#define SDADC_MAX_CHANNEL_CNT        2U

#define SDADC_UNALLOCATEDPAR_CORE_ID ((uint32)0xFFU)
/**
* @brief        All CoreIDs are supported by SDADC driver.
*/
#define SDADC_ECUCPARTITION_0_CORE_ID     ((uint32)0U)

/**
* @brief        All CoreIDs are supported by SDADC driver.
*/
#define SDADC_MAX_CORES     ((uint32)2U)

/**
 * @brief   SDADC Precompile support
 */
#define SDADC_PRECOMPILE_SUPPORT (STD_ON)

/**
 * @brief   Switches the Development Error Detection and Notification ON or OFF.
 */
#define SDADC_DEV_ERROR_DETECT (STD_ON)

/**
 * @brief   Switches the Development Error Detection and Notification ON or OFF.
 */
#define SDADC_MULTICORE_SUPPORT (STD_ON)

/**
 * @brief          Support for version info API.
 * @details        Switches the Sdadc_GetVersionInfo() API ON or OFF.
 */
#define SDADC_VERSION_INFO_API (STD_ON)
/**
 * @brief          Support for Timestamp Polling.
 * @details        Switches the Timestamp Polling feature.
 */
#define SDADC_TS_POLLING (STD_OFF)
/**
 * @brief          Support for calibration .
 * @details        Switches the Calibration feature.
 */
#define SDADC_CALIBRATION_FEATURE (STD_ON)
/**
 * @brief
 * @details
 */
#define SDADC_DISABLE_DEM_REPORT_ERROR_STATUS (STD_OFF)
/**
 * @brief   Number of loops before returning SDADC_E_TIMEOUT.
 */
#define SDADC_TIMEOUT_LOOPS 10000U

#define SDADC_INTG_MCOC_TIMEOUT_LOOPS 100000U

#define SDADC_GLOBAL_TIMESTAMP_LOOPS 100000U

#if (SDADC_DISABLE_DEM_REPORT_ERROR_STATUS == STD_OFF)
#define SDADC_E_TIMEOUT_VALUE DemConf_DemEventParameter_DemEventParameter_SdadcTimeout
#endif /* SDADC_DISABLE_DEM_REPORT_ERROR_STATUS == STD_OFF */

#define SDADC_UNIT_0_CH_0_ISR_USED
#define SDADC_UNIT_0_CH_1_ISR_USED

#if (STD_ON == SDADC_MULTICORE_SUPPORT)
#define SDADC_GetCoreID()                 GET_CPU_ID()
#else
#define SDADC_GetCoreID()                 0
#endif

typedef void (*SDADC_NotifyType)(void); /**< @brief Notification function pointer definition */

typedef struct
{
    uint32 u32CBRReg;
    uint32 u32CGNRReg;
} Sdadc_ChannelCalibInfoType, *Sdadc_ChannelCalibInfoTypePtr;

typedef Sdadc_ChannelCalibInfoType const*Sdadc_ChannelCalibInfoTypeConstPtr;

typedef struct
{
    uint8  u8HwChannelId;
    uint8  u8AccessMode;
    uint8  u8COCIntSupress;
    uint8  u8GlobalTs;
    uint32 u32CCRReg;
    uint32 u32CDRReg;
    uint32 u32CFRReg;
    uint32 u32CPRReg;
    uint32 u32CLLMTReg;
    uint32 u32CHLMTReg;
    uint32 u32CRTCSRReg;
    uint32 u32CSDRReg;
    uint32 u32CICFRReg;
    uint32 u32CMACSRReg;
    uint32 u32CTSCNTReg;
    Sdadc_ChannelCalibInfoTypeConstPtr *pCalibPtr;
    SDADC_NotifyType BufferFullNotification;
    SDADC_NotifyType ConversionCompleteNotification;
    SDADC_NotifyType FifoOverFlowNotification;
    SDADC_NotifyType ZerocrossNotification;
    SDADC_NotifyType HighLimitNotification;
    SDADC_NotifyType LowLimitNotification;
    SDADC_NotifyType WindowLimitNotification;
    SDADC_NotifyType ShortCircuitNotification;
    SDADC_NotifyType SaturationNotification;
    SDADC_NotifyType ClockAbsenceNotification;
    SDADC_NotifyType TimestampValidNotification;
    SDADC_NotifyType TsignP2NNotification;
} Sdadc_ChannelConfigType, *Sdadc_ChannelConfigTypePtr;

typedef Sdadc_ChannelConfigType const* Sdadc_ChannelConfigTypeConstPtr;

typedef struct
{
    uint32                                 CoreId;
    uint8                                  HWInstanceId;
#if (STD_ON == SDADC_GLOBAL_TS_SUPPORT)
    uint8                                  u8UseDma;
    Dma_InstanceType                       eDmaInstance;
    uint8                                  u8DmaChannel;
#else
    uint8                                  u8Rsv0;
    uint8                                  u8Rsv1;
    uint8                                  u8Rsv2;
#endif
    uint32                                 DelayCntFactor;
    uint32                                 FunctionClk;
    uint32                                 u32CTRLReg;
    uint32                                 u32NIERReg;
    uint32                                 u32ABNIER0Reg;
    uint32                                 u32ABNIER1Reg;
    uint32                                 u32PWMGENReg;
    uint32                                 u32BACSRReg;
    uint32                                 u32EXTIEReg;
    uint32                                 u32TMRSRCSEL;
    uint32                                 u32TSTAMPSEL;
    const Sdadc_ChannelConfigTypeConstPtr *paSdadcChannelCfg;
} Sdadc_HwConfigType;

/*==================================================================================================
*                                       GLOBAL FUNCTIONS
==================================================================================================*/
#define CDD_SDADC_START_SEC_CODE
#include "Sdadc_MemMap.h"

CDD_SDADC_TEXT_SECTION extern void SDADC0_CH0_COC_Notification(void);


CDD_SDADC_TEXT_SECTION extern void SDADC0_CH0_TimeStamp_Notification(void);


CDD_SDADC_TEXT_SECTION extern void SDADC0_CH1_BF_Notification(void);


CDD_SDADC_TEXT_SECTION extern void SDADC0_CH1_COC_Notification(void);


#define CDD_SDADC_STOP_SEC_CODE
#include "Sdadc_MemMap.h"

#ifdef __cplusplus
}
#endif

#endif /* SDADC_CFG_H */

/** @} */
