/**
*   @file    Eth_PBcfg.c
*   @version 1.5.1
*
*   @brief   AUTOSAR Eth - Post Build configuration Eth source file.
*   @details Post Build configuration file for Eth driver.
*
*   @addtogroup ETH
*   @{
*/
/*==================================================================================================
*   PERIPHERAL           : ETH
*   PLATFORM             : Flagchip FC7300
*   AUTOSAR VERSION      : 4.6.0
*   AUTOSAR REVISION     : ASR_REL_4_6_0
*   SOFTWARE VERSION     : 1.5.1
*   VENDOR               : Flagchip Semiconductors
*
*   Copyright 2020-2026 Flagchip Semiconductors Co., Ltd.
*   All Rights Reserved.
==================================================================================================*/

/*==================================================================================================
*   Revision History:
*
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------- ----------   ---------------
*   0.1.0       02/06/2023    QXW0085/32    N/A          Initialization of ETH Driver
*   0.2.0       27/09/2023    QXW0085/32    N/A          Implementation of Multicore instance
*   0.3.0       20/10/2023    QXW0085/32    N/A          Optimization of Multicore instance
*   0.4.0       17/11/2023    QXW0085       N/A          Requirements modification and bugs fix
*   0.5.0       15/01/2024    QXW0085       N/A          Bugs fix and code Optimization
*   0.6.0       21/03/2024    QXW0085       N/A          Bugs fix and code Optimization
*   0.8.0       17/07/2024    QXW0085       N/A          Update Misra-C detection
*   1.5.0       21/01/2026    QXW0085       N/A          Support Time Based Schedule
==================================================================================================*/

#ifdef __cplusplus
extern "C"{
#endif

/*==================================================================================================
*                                        INCLUDE FILES
==================================================================================================*/

#include "Eth_PBcfg.h"
#include "Eth_Cfg.h"
#include "EthTrcv.h"

/*==================================================================================================
*                                       LOCAL VARIABLES
==================================================================================================*/

#define ETH_START_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
#include "Eth_MemMap.h"

/* PRQA S 0779 ++ #Misra-C:2012 Rule-5.2 Identifiers declared in the same scope and name space
*  shall be distinct
*  0779:Identifier does not differ from other identifier(s) within the specified number of
*  significant characters.
*  REASON:These identifiers are automatically generated by configuration tool, and they are
*  distinct.
*/

/* [SWS_Eth_00218][SWDESG_ETH_178][SWDESG_ETH_179]The egress and ingress buffers shall fulfill the
*  memory alignment requirements.
*/

/* EthCtrlConfig_0 Ethernet controller Egress buffer */
ETH_DATA_SECTION ALIGN(4) static Eth_DMADescType EthCtrlConfig_0_EthCtrlConfigEgressFifo_0_DescMemory[6U];
ETH_DATA_SECTION ALIGN(4) static uint8 EthCtrlConfig_0_EthCtrlConfigEgressFifo_0_BufferMemory[6U * 1536U];

ETH_DATA_SECTION ALIGN(4) static Eth_DMADescType EthCtrlConfig_0_EthCtrlConfigEgressFifo_1_DescMemory[6U];
ETH_DATA_SECTION ALIGN(4) static uint8 EthCtrlConfig_0_EthCtrlConfigEgressFifo_1_BufferMemory[6U * 1536U];

/* EthCtrlConfig_0 Ethernet controller Ingress buffer */
ETH_DATA_SECTION ALIGN(4) static Eth_DMADescType EthCtrlConfig_0_EthCtrlConfigIngressFifo_0_DescMemory[16U];
ETH_DATA_SECTION ALIGN(4) static uint8 EthCtrlConfig_0_EthCtrlConfigIngressFifo_0_BufferMemory[16U * 1536U];

ETH_DATA_SECTION ALIGN(4) static Eth_DMADescType EthCtrlConfig_0_EthCtrlConfigIngressFifo_1_DescMemory[16U];
ETH_DATA_SECTION ALIGN(4) static uint8 EthCtrlConfig_0_EthCtrlConfigIngressFifo_1_BufferMemory[16U * 1536U];

/* PRQA S 0779 -- */

#define ETH_STOP_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
#include "Eth_MemMap.h"

#define ETH_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "Eth_MemMap.h"

/* EthCtrlConfig_0 Ethernet controller Egress Configurations */
ETH_DATA_SECTION static const Eth_FifoConfigType EthCtrlConfig_0_EgressFifoConfigs[2U] =
{
    {
        /* .FifoBufLenByte = */ 1536U,
        /* .FifoBufTotal = */ 6U,
        /* .DescListAddress = */ EthCtrlConfig_0_EthCtrlConfigEgressFifo_0_DescMemory,
        /* .FifoBufStartAddress = */ EthCtrlConfig_0_EthCtrlConfigEgressFifo_0_BufferMemory,
        /* .Priority = */ 0x01
    },
    {
        /* .FifoBufLenByte = */ 1536U,
        /* .FifoBufTotal = */ 6U,
        /* .DescListAddress = */ EthCtrlConfig_0_EthCtrlConfigEgressFifo_1_DescMemory,
        /* .FifoBufStartAddress = */ EthCtrlConfig_0_EthCtrlConfigEgressFifo_1_BufferMemory,
        /* .Priority = */ 0x02
    }
};

/* EthCtrlConfig_0 Ethernet controller Ingress Configurations */
ETH_DATA_SECTION static const Eth_FifoConfigType EthCtrlConfig_0_IngressFifoConfigs[2U] =
{
    {
        /* .FifoBufLenByte = */ 1536U,
        /* .FifoBufTotal = */ 16U,
        /* .DescListAddress = */ EthCtrlConfig_0_EthCtrlConfigIngressFifo_0_DescMemory,
        /* .FifoBufStartAddress = */ EthCtrlConfig_0_EthCtrlConfigIngressFifo_0_BufferMemory,
        /* .Priority = */ 0x01
    },
    {
        /* .FifoBufLenByte = */ 1536U,
        /* .FifoBufTotal = */ 16U,
        /* .DescListAddress = */ EthCtrlConfig_0_EthCtrlConfigIngressFifo_1_DescMemory,
        /* .FifoBufStartAddress = */ EthCtrlConfig_0_EthCtrlConfigIngressFifo_1_BufferMemory,
        /* .Priority = */ 0x02
    }
};

/* EthCtrlConfig_0 Mtl configurations */
ETH_DATA_SECTION static const Eth_MTLQueueCfgType EthCtrlConfig_0_MTLQueueConfigs[2U] =
{
    {
        /* .TxQueueMode = */ ETH_MTL_QUEUE_ENABLE_GENERIC,
        /* .TxQueueWeights = */ 0U,
        /* .IdleSlopeCredit = */ 0U,
        /* .SendSlopeCredit = */ 0U,
        /* .HiCredit = */ 0U,
        /* .LoCredit = */ 0,
        /* .RxQueueMode = */ ETH_MTL_QUEUE_ENABLE_GENERIC,
        /* .ForwardTCPIPChecksumErr = */ (boolean)FALSE,
        /* .ForwardErrorPackets = */ (boolean)FALSE,
        /* .ForwardUndersizedGood = */ (boolean)FALSE,
        /* .RxQueueWeight = */ 0U
    },
    {
        /* .TxQueueMode = */ ETH_MTL_QUEUE_ENABLE_GENERIC,
        /* .TxQueueWeights = */ 0U,
        /* .IdleSlopeCredit = */ 0U,
        /* .SendSlopeCredit = */ 0U,
        /* .HiCredit = */ 0U,
        /* .LoCredit = */ 0,
        /* .RxQueueMode = */ ETH_MTL_QUEUE_ENABLE_GENERIC,
        /* .ForwardTCPIPChecksumErr = */ (boolean)FALSE,
        /* .ForwardErrorPackets = */ (boolean)FALSE,
        /* .ForwardUndersizedGood = */ (boolean)FALSE,
        /* .RxQueueWeight = */ 0U
    }
};

/* EthCtrlConfig_0 Dma configurations */
ETH_DATA_SECTION static const Eth_DMAChConfigType EthCtrlConfig_0_DmaChConfigs[ETH_FEATURE_MAX_CHANNEL_COUNT] =
{
    {
        /* .Control = */ 0x00080000U,
        /* .TxControl = */ 0x00200010U,
        /* .RxControl = */ 0x00200c00U
    },
    {
        /* .Control = */ 0x00080000U,
        /* .TxControl = */ 0x00200010U,
        /* .RxControl = */ 0x00200c00U
    }
};

/* ETH controller configurations */
ETH_DATA_SECTION static const Eth_CtrlCfgType Eth_Ctrl_Configs[1U] =
{
    {
        /* .BusClkFreq = */150000000U,
        /* .EcucPartition = */ 3U,
        /* .EthIfIdx = */ 0U,
        /* .EnableMii = */ (boolean)TRUE,
        /* .EnableMmd = */ (boolean)TRUE,

#if (STD_ON == ETH_CTRL_ENABLE_MII)
        /* .ReadMiiCbk = */ EthTrcv_ReadMiiIndication,
        /* .WriteMiiCbk = */ EthTrcv_WriteMiiIndication,
#endif  /* STD_ON == ETH_CTRL_ENABLE_MII */

#if (STD_ON == ETH_TRANSCEIVER_PREINIT)
        /* .Preinit_Func = */ NULL_PTR,
#endif  /* STD_ON == ETH_TRANSCEIVER_PREINIT */

        /* .TxInterruptEn = */ (boolean)TRUE,
        /* .RxInterruptEn = */ (boolean)TRUE,
        /* .EgressFifoCount = */ 2U,
        /* .IngressFifoCount = */ 2U,
        /* .EgressFifoCfgPtr = */ EthCtrlConfig_0_EgressFifoConfigs,
        /* .IngressFifoCfgPtr = */ EthCtrlConfig_0_IngressFifoConfigs,
        /* .PhyIf = */ ETH_PHYIF_RGMII,
        /* .MacAddress = */ {0x00U,0x11U,0x22U,0x33U,0x55U,0x66U},
        /* .MacConfiguration = */ 0x30302000U,
        /* .MacExtConfiguration = */ 0x00000000U,
        /* .MacFilterRegValue = */ 0x00000404U,
        /* .DmaMode = */ 0x00010800U,
        /* .DmaSysBusMode = */ 0x00005000U,
        /* .DmaCfgPtr = */ EthCtrlConfig_0_DmaChConfigs,
        /* .MtlOperationMode = */ 0x00000060U,
        /* .MTLQueueCfgPtr = */ EthCtrlConfig_0_MTLQueueConfigs,
        /* .MMCResetOnRead = */ (boolean)FALSE,
        /* .MMCStopRollover = */ (boolean)FALSE,

        /* .TxClkOutputEn = */ (boolean)TRUE,
        /* .TxClkSrcDiv = */ 0U,
        /* .TxClkSrcSel = */ ETH_TXCLK_PLL0_DIV_PLL0_CLK0,
        /* .TxClkSel = */ ETH_TXCLK_OUTPUT_SEL_TX_CLK,
        /* .RgmiiClkSel = */ ETH_RGMII_SEL_PLL1_DIVH,

#if (STD_ON == ETH_GLOBAL_TIME_SUPPORT)
        /* .PtpClkSrc = */ ETH_PTP_CLK_SEL_PCC,
        /* .PtpCtrl = */ 0x00012702U,
        {
            /* .nanoseconds = */ 0x00000000U,
            /* .seconds = */ 0x00000000U,
            /* .secondsHi = */ 0x00000000U
        },
        /* .SubSecondInc = */ 0x00140000U,
        /* .TimestampAddend = */ 0x55555555U,
        /* .EgressCorrNanoseconds = */ 0x00000000U,
        /* .IngressCorrNanoseconds = */ 0x00000000U,
#endif  /* STD_ON == ETH_GLOBAL_TIME_SUPPORT = */

#if (STD_ON == ETH_FEATURE_TIME_AWARE_SHAPER_SUPPORT)
        /* .NumTimeAwareShaper = */ 0U,
        /* .TimeAwareShaperPtr = */ NULL_PTR,
#endif  /* STD_ON == ETH_FEATURE_TIME_AWARE_SHAPER_SUPPORT */

#if (STD_ON == ETH_SWITCH_MANAGEMENT_SUPPORT)
        /* .SwtMgmtPtr = */ NULL_PTR,
#endif  /* STD_ON == ETH_SWITCH_MANAGEMENT_SUPPORT */

#if (STD_ON == ETH_FEATURE_SAFETY_SUPPORT)
        /* .SafetyEccEn  = */ (boolean)TRUE,
        /* .SafetyFsmParityEn = */ (boolean)TRUE,
        /* .SafetyFsmTimeoutEn = */ (boolean)TRUE,
        /* .SafetyDppMode = */ ETH_MTL_DPP_ODD_PARITY,
#if (STD_ON == ETH_DEM_EVENT_DETECT)
        {
            /* .state = */ STD_ON,
            /* .id = */ DemConf_DemEventParameter_DemEventParameter_EthSafety
        },
#endif  /* STD_ON == ETH_DEM_EVENT_DETECT */
#endif  /* STD_ON == ETH_FEATURE_SAFETY_SUPPORT */

#if (STD_ON == ETH_DEM_EVENT_DETECT)
        {
            /* .state = */ STD_OFF,
            /* .id = */ 0
        },
        {
            /* .state = */ STD_OFF,
            /* .id = */ 0
        },
        {
            /* .state = */ STD_OFF,
            /* .id = */ 0
        },
        {
            /* .state = */ STD_OFF,
            /* .id = */ 0
        },
        {
            /* .state = */ STD_OFF,
            /* .id = */ 0
        },
        {
            /* .state = */ STD_OFF,
            /* .id = */ 0
        },
        {
            /* .state = */ STD_OFF,
            /* .id = */ 0
        },
        {
            /* .state = */ STD_OFF,
            /* .id = */ 0
        },
        {
            /* .state = */ STD_OFF,
            /* .id = */ 0
        }
#endif  /* STD_ON == ETH_DEM_EVENT_DETECT */

    }
};

/*==================================================================================================
*                                      GLOBAL VARIABLES
==================================================================================================*/

/* Eth Initialization Configuration */
ETH_DATA_SECTION const Eth_ConfigType Eth_Config =
{
    /* .NumController = */ 1U,
    /* .CtrlPtr = */ Eth_Ctrl_Configs
};

#define ETH_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "Eth_MemMap.h"


#ifdef __cplusplus
}
#endif

/** @} */
