/**
*   @file    Spi_PBcfg.c
*   @version 1.5.1
*
*   @brief   AUTOSAR Spi - Post Build configuration Spi source file.
*   @details Post Build configuration file for Spi driver.
*
*   @addtogroup SPI
*   @{
*/
/*==================================================================================================
*   PERIPHERAL           : SPI
*   PLATFORM             : Flagchip FC7300
*   AUTOSAR VERSION      : 4.6.0
*   AUTOSAR REVISION     : ASR_REL_4_6_0
*   SOFTWARE VERSION     : 1.5.1
*   VENDOR               : Flagchip Semiconductors
*
*   Copyright 2020-2023 Flagchip Semiconductors Co., Ltd.
*   All Rights Reserved.
==================================================================================================*/
/*==================================================================================================
*   Revision History:
*
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------- ----------   ---------------
*   0.1.0       14/07/2023    QXW0071       N/A          SPI Initial Version
*   0.2.0       03/10/2023    QXW0071       N/A          Add support for multi-core
*   0.3.0       19/10/2023    QXW0071       N/A          Optimize code to comply with Misra-C rules
*   0.4.0       17/11/2023    QXW0071       N/A          Add workaround when enable CS Continuous and sample on first edge.
*   0.5.0       01/16/2024    QXW0071       N/A          Optimize Code
*   0.6.0       02/28/2024    QXW0103       N/A          Add support for FC7240
==================================================================================================*/

#ifdef __cplusplus
extern "C"{
#endif
/* PRQA S 0791 EOF 
   0791:Macro identifier does not differ from other macro identifier(s) (e.g. '%1s') within the 
	specified number of significant characters.
   REASON:These macros have the same first 30 characters,but they are differrent in follow characters.Modern compiler will recognize the difference.
*/

/* PRQA S 0779 ++ #Misra-C:2012 Rule-5.2 Identifiers declared in the same scope and name space
*  shall be distinct
*  0779:Identifier does not differ from other identifier(s) within the specified number of
*  significant characters.
*  REASON:These identifiers are automatically generated by configuration tool, and they are
*  distinct.
*/

/* PRQA S 3678 EOF #Misra-C:2012 Rule-8.13 A pointer should point to a const-qualified type whenever possible
 * Reason: That object can not be declared with const type */
/*==================================================================================================
*                                        INCLUDE FILES
==================================================================================================*/

#include "Spi.h"
#include "Spi_RegOps.h"

#if (SPI_DEM_ENABLE == STD_ON)
#include "Dem.h"
#endif /* SPI_DEM_ENABLE == STD_ON */

/*==================================================================================================
*                                    SOURCE FILE VERSION INFORMATION
==================================================================================================*/

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/


/*==================================================================================================
*                                      GLOBAL FUNCTIONS
==================================================================================================*/
#define SPI_START_SEC_CODE
#include "Spi_MemMap.h"



#define SPI_STOP_SEC_CODE
#include "Spi_MemMap.h"

/*==================================================================================================
*                                      LOCAL VARIABLES
==================================================================================================*/
#if ((SPI_DMA_USED == STD_ON) && (SPI_ASYNC_DRIVER == STD_ON))
    #define SPI_START_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
#else
    #define SPI_START_SEC_VAR_NO_INIT_UNSPECIFIED
#endif /* ((SPI_DMA_USED == STD_ON) && (SPI_ASYNC_DRIVER == STD_ON)) */
#include "Spi_MemMap.h"



/*  Buffers Descriptors for EB Channels (if any) */
/* Allocate Buffers for IB Channels (if any) */
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferTX_PBSpiChannel_0[4], 4)
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferRX_PBSpiChannel_0[4], 4)
/* Allocate Buffers for IB Channels (if any) */
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferTX_PBSpiChannel_1[2], 4)
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferRX_PBSpiChannel_1[2], 4)
SPI_DATA_SECTION VAR_ALIGN(static Spi_ChannelbufferType Buffer_PBSpiChannel_2, 4)
/* Allocate Buffers for IB Channels (if any) */
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferTX_PBSpiChannel_3[4], 4)
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferRX_PBSpiChannel_3[4], 4)


#if ((SPI_DMA_USED == STD_ON) && (SPI_ASYNC_DRIVER == STD_ON))
    #define SPI_STOP_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
#else
    #define SPI_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#endif /* ((SPI_DMA_USED == STD_ON) && (SPI_ASYNC_DRIVER == STD_ON)) */
#include "Spi_MemMap.h"

#define SPI_START_SEC_VAR_INIT_UNSPECIFIED
#include "Spi_MemMap.h"



/*  Buffers Descriptors for IB Channels (if any) */
SPI_DATA_SECTION static Spi_ChannelbufferType Buffer_PBSpiChannel_0 =
{
    BufferTX_PBSpiChannel_0,
    BufferRX_PBSpiChannel_0
};
SPI_DATA_SECTION static Spi_ChannelbufferType Buffer_PBSpiChannel_1 =
{
    BufferTX_PBSpiChannel_1,
    BufferRX_PBSpiChannel_1
};
SPI_DATA_SECTION static Spi_ChannelbufferType Buffer_PBSpiChannel_3 =
{
    BufferTX_PBSpiChannel_3,
    BufferRX_PBSpiChannel_3
};


#define SPI_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "Spi_MemMap.h"

/*==================================================================================================
*                                      LOCAL CONSTANTS
==================================================================================================*/

#define SPI_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "Spi_MemMap.h"




/* SpiChannelConfig_PB Channel Configuration of SpiChannel_0*/
SPI_DATA_SECTION static const Spi_ChnlCfgType Spi_ChannelConfig_SpiChannel_0 =
{
    /* SpiChannel_0*/
    IB,
    (uint32)0x55u,
    4U,
    &Buffer_PBSpiChannel_0,
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aChnlStats[0]
};

/* SpiChannelConfig_PB Channel Configuration of SpiChannel_1*/
SPI_DATA_SECTION static const Spi_ChnlCfgType Spi_ChannelConfig_SpiChannel_1 =
{
    /* SpiChannel_1*/
    IB,
    (uint32)0x55u,
    2U,
    &Buffer_PBSpiChannel_1,
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aChnlStats[1]
};

/* SpiChannelConfig_PB Channel Configuration of SpiChannel_2*/
SPI_DATA_SECTION static const Spi_ChnlCfgType Spi_ChannelConfig_SpiChannel_2 =
{
    /* SpiChannel_2*/
    EB,
    (uint32)0x55u,
    4U,
    &Buffer_PBSpiChannel_2,
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aChnlStats[2]
};

/* SpiChannelConfig_PB Channel Configuration of SpiChannel_3*/
SPI_DATA_SECTION static const Spi_ChnlCfgType Spi_ChannelConfig_SpiChannel_3 =
{
    /* SpiChannel_3*/
    IB,
    (uint32)0x55u,
    4U,
    &Buffer_PBSpiChannel_3,
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aChnlStats[3]
};

/* Spi_apChannelConfigList Channel Configuration of Spi*/
SPI_DATA_SECTION static const Spi_ChannelsCfgType Spi_aChannelConfigList[4] =
{
    /* SpiChannel_0 */
    {
        &Spi_ChannelConfig_SpiChannel_0
    },

    /* SpiChannel_1 */
    {
        &Spi_ChannelConfig_SpiChannel_1
    },

    /* SpiChannel_2 */
    {
        &Spi_ChannelConfig_SpiChannel_2
    },

    /* SpiChannel_3 */
    {
        &Spi_ChannelConfig_SpiChannel_3
    }
};




/* Channel to Job Assignment */

SPI_DATA_SECTION static const Spi_ChannelType SpiJob_0_Flash_Read_ID_ChnlsArray_PB[2] = {SpiConf_SpiChannel_SpiChannel_0,SpiConf_SpiChannel_SpiChannel_1};
SPI_DATA_SECTION static const Spi_ChannelType SpiJob_1_Spi2_ChnlsArray_PB[1] = {SpiConf_SpiChannel_SpiChannel_2};
SPI_DATA_SECTION static const Spi_ChannelType SpiJob_2_Spi5_ChnlsArray_PB[1] = {SpiConf_SpiChannel_SpiChannel_3};




/* External device Configuration of Spi_Flash_GD25Q32*/
SPI_DATA_SECTION static const Spi_DeviceAttrType Spi_ExternalDeviceConfig_Spi_Flash_GD25Q32 =
{
            /* Spi_Flash_GD25Q32 */
            SPI_SPURIOUS_CORE_ID_U32,
            (uint32)(FCSPI_TRCTRL_CPOL_LOW_U32 |     /* Clock Polarity (Idle State) */
            FCSPI_TRCTRL_CPHA_TRAILING_U32 |         /* Clock Phase */
            FCSPI_TRCTRL_PRESCALE_1_U32 |            /* Baudrate: Should=100000.0, Is=100000, Error=0.0% */
            FCSPI_TRCTRL_BYSW_DIS_U32  |             /* Byte Swap Enable or Disable */
            (uint32)(FCSPI_TRCTRL_PCS1_EN_U32 |      /* Chip Select Pin Via Peripheral Engine*/
                    FCSPI_TRCTRL_CONT_EN_U32)        /* Enable continuous chip select */
            ) & FCSPI_TRCTRL_RWBITS_MASK_U32,

            ( ((uint32)(35) << 24u) |                 /* TimeClk2Cs: Should=3000ns, Is=3000, Error=0.0% */
            ((uint32)(35) << 16u) |                   /* TimeCs2Clk: Should=3000ns, Is=3000, Error=0.0% */
            ((uint32)(35) << 8u) |                    /* TimeCs2Cs: Should=3000ns, Is=3000, Error=0.0% */
            ((uint32)(118))
            ),

            /* CFG1 register configuration */
            (uint32)0u                              /* Chip select polarity */
            | FCSPI_CFG1_PINCFG_SIN_INPUT_SOUT_OUTPUT_U32 | FCSPI_CFG1_MATCFG_DIS_U32 
            | FCSPI_CFG1_MASTER_EN_U32
};

/* External device Configuration of SpiExternalDevice_0_Spi2*/
SPI_DATA_SECTION static const Spi_DeviceAttrType Spi_ExternalDeviceConfig_SpiExternalDevice_0_Spi2 =
{
            /* SpiExternalDevice_0_Spi2 */
            SPI_SPURIOUS_CORE_ID_U32,
            (uint32)(FCSPI_TRCTRL_CPOL_LOW_U32 |     /* Clock Polarity (Idle State) */
            FCSPI_TRCTRL_CPHA_LEADING_U32 |         /* Clock Phase */
            FCSPI_TRCTRL_PRESCALE_1_U32 |            /* Baudrate: Should=100000.0, Is=100000, Error=0.0% */
            FCSPI_TRCTRL_BYSW_DIS_U32  |             /* Byte Swap Enable or Disable */
            (uint32)(FCSPI_TRCTRL_PCS1_EN_U32 |      /* Chip Select Pin Via Peripheral Engine*/
                    FCSPI_TRCTRL_CONT_EN_U32)        /* Enable continuous chip select */
            ) & FCSPI_TRCTRL_RWBITS_MASK_U32,

            ( ((uint32)(11) << 24u) |                 /* TimeClk2Cs: Should=1000ns, Is=1000, Error=0.0% */
            ((uint32)(11) << 16u) |                   /* TimeCs2Clk: Should=1000ns, Is=1000, Error=0.0% */
            ((uint32)(11) << 8u) |                    /* TimeCs2Cs: Should=1000ns, Is=1000, Error=0.0% */
            ((uint32)(118))
            ),

            /* CFG1 register configuration */
            (uint32)0u                              /* Chip select polarity */
            | FCSPI_CFG1_PINCFG_SIN_INPUT_SOUT_OUTPUT_U32 | FCSPI_CFG1_MATCFG_DIS_U32 
            | FCSPI_CFG1_MASTER_EN_U32
};

/* External device Configuration of SpiExternalDevice_1_Spi5*/
SPI_DATA_SECTION static const Spi_DeviceAttrType Spi_ExternalDeviceConfig_SpiExternalDevice_1_Spi5 =
{
            /* SpiExternalDevice_1_Spi5 */
            SPI_SPURIOUS_CORE_ID_U32,
            (uint32)(FCSPI_TRCTRL_CPOL_LOW_U32 |     /* Clock Polarity (Idle State) */
            FCSPI_TRCTRL_CPHA_LEADING_U32 |         /* Clock Phase */
            FCSPI_TRCTRL_BYSW_DIS_U32  |             /* Byte Swap Enable or Disable */
            FCSPI_TRCTRL_PCS0_EN_U32          /* Chip Select Pin Via Peripheral Engine*/
            ) & FCSPI_TRCTRL_RWBITS_MASK_U32,

            (uint32)0x00000000u,                              /* CLK_CFG */
            (uint32)0u                              /* Chip select polarity */
            | FCSPI_CFG1_PINCFG_SIN_INPUT_SOUT_OUTPUT_U32 | FCSPI_CFG1_MATCFG_DIS_U32 
};

/* Spi_apExternalDeviceConfigList External device Configuration of Spi*/
SPI_DATA_SECTION static const Spi_ExDevicesAttrsType Spi_aExternalDeviceConfigList[3U] =
{
    /* Spi_Flash_GD25Q32 */
    {
        &Spi_ExternalDeviceConfig_Spi_Flash_GD25Q32
    },

    /* SpiExternalDevice_0_Spi2 */
    {
        &Spi_ExternalDeviceConfig_SpiExternalDevice_0_Spi2
    },

    /* SpiExternalDevice_1_Spi5 */
    {
        &Spi_ExternalDeviceConfig_SpiExternalDevice_1_Spi5
    }
};





/* Job Configuration of SpiJob_0_Flash_Read_ID*/
SPI_DATA_SECTION static const Spi_JobCfgType Spi_JobConfig_SpiJob_0_Flash_Read_ID =
{
    /* SpiJob_0_Flash_Read_ID */
    (Spi_ChannelType)2u,
    SpiJob_0_Flash_Read_ID_ChnlsArray_PB,                                            /* List of Channels */
    NULL_PTR,                                                        /* job end notify callback */
    NULL_PTR,                                                        /* Start Notification */
    (sint8)0,                                                        /* Priority */
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aJobStats[0],                            /* JobState instance */
    CSIB0,                                                          /* Virtual FCSPI Hardware Module index */
    FCSPI_1_OFFSET,                                                 /* FCSpi device HW unit offset */
    /* External Device Settings */
    SPI_Spi_Flash_GD25Q32,                                        /* External Device */
    &Spi_aExternalDeviceConfigList[SPI_Spi_Flash_GD25Q32]      /* pcExternalDeviceConfig - pointer to the external device configuration */
#if (SPI_SUP_CONT_EN_SECOND_EDGE_SAMPLE == STD_OFF)
    ,FALSE                   /* If this job is CONT = 1 and SCK_PHA = 1 */
#endif
};

/* Job Configuration of SpiJob_1_Spi2*/
SPI_DATA_SECTION static const Spi_JobCfgType Spi_JobConfig_SpiJob_1_Spi2 =
{
    /* SpiJob_1_Spi2 */
    (Spi_ChannelType)1u,
    SpiJob_1_Spi2_ChnlsArray_PB,                                            /* List of Channels */
    NULL_PTR,                                                        /* job end notify callback */
    NULL_PTR,                                                        /* Start Notification */
    (sint8)0,                                                        /* Priority */
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aJobStats[1],                            /* JobState instance */
    CSIB1,                                                          /* Virtual FCSPI Hardware Module index */
    FCSPI_2_OFFSET,                                                 /* FCSpi device HW unit offset */
    /* External Device Settings */
    SPI_SpiExternalDevice_0_Spi2,                                        /* External Device */
    &Spi_aExternalDeviceConfigList[SPI_SpiExternalDevice_0_Spi2]      /* pcExternalDeviceConfig - pointer to the external device configuration */
#if (SPI_SUP_CONT_EN_SECOND_EDGE_SAMPLE == STD_OFF)
    ,FALSE                   /* If this job is CONT = 1 and SCK_PHA = 1 */
#endif
};

/* Job Configuration of SpiJob_2_Spi5*/
SPI_DATA_SECTION static const Spi_JobCfgType Spi_JobConfig_SpiJob_2_Spi5 =
{
    /* SpiJob_2_Spi5 */
    (Spi_ChannelType)1u,
    SpiJob_2_Spi5_ChnlsArray_PB,                                            /* List of Channels */
    NULL_PTR,                                                        /* job end notify callback */
    NULL_PTR,                                                        /* Start Notification */
    (sint8)0,                                                        /* Priority */
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aJobStats[2],                            /* JobState instance */
    CSIB2,                                                          /* Virtual FCSPI Hardware Module index */
    FCSPI_5_OFFSET,                                                 /* FCSpi device HW unit offset */
    /* External Device Settings */
    SPI_SpiExternalDevice_1_Spi5,                                        /* External Device */
    &Spi_aExternalDeviceConfigList[SPI_SpiExternalDevice_1_Spi5]      /* pcExternalDeviceConfig - pointer to the external device configuration */
#if (SPI_SUP_CONT_EN_SECOND_EDGE_SAMPLE == STD_OFF)
    ,FALSE                   /* If this job is CONT = 1 and SCK_PHA = 1 */
#endif
};

/* Spi_apJobConfigList Job Configuration of Spi*/
SPI_DATA_SECTION static const Spi_JobsCfgType Spi_aJobConfigList[3] =
{
    /* SpiJob_0_Flash_Read_ID */
    {
        &Spi_JobConfig_SpiJob_0_Flash_Read_ID
    },

    /* SpiJob_1_Spi2 */
    {
        &Spi_JobConfig_SpiJob_1_Spi2
    },

    /* SpiJob_2_Spi5 */
    {
        &Spi_JobConfig_SpiJob_2_Spi5
    }
};



/* Job to Sequence Assignment */
SPI_DATA_SECTION static const Spi_JobType SpiSequence_0_Spi_Flash_JobsArray_PB[1] = {SpiConf_SpiJob_SpiJob_0_Flash_Read_ID};
SPI_DATA_SECTION static const Spi_JobType SpiSequence_1_Spi2_Master_JobsArray_PB[1] = {SpiConf_SpiJob_SpiJob_1_Spi2};
SPI_DATA_SECTION static const Spi_JobType SpiSequence_2_Spi5_Slave_JobsArray_PB[1] = {SpiConf_SpiJob_SpiJob_2_Spi5};




/* Sequence Configuration of SpiSequence_0_Spi_Flash */
SPI_DATA_SECTION static const Spi_SeqCfgType Spi_SequenceConfig_SpiSequence_0_Spi_Flash =
{
    /* SpiSequence_0_Spi_Flash */
    (Spi_JobType)1u,
    SPI_SPURIOUS_CORE_ID_U32,
    SpiSequence_0_Spi_Flash_JobsArray_PB,                     /* the jobs array of a sequence */
    NULL_PTR,                          /* sequence end notify callack */
    (uint8)FALSE                     /* Interruptible */
};

/* Sequence Configuration of SpiSequence_1_Spi2_Master */
SPI_DATA_SECTION static const Spi_SeqCfgType Spi_SequenceConfig_SpiSequence_1_Spi2_Master =
{
    /* SpiSequence_1_Spi2_Master */
    (Spi_JobType)1u,
    SPI_SPURIOUS_CORE_ID_U32,
    SpiSequence_1_Spi2_Master_JobsArray_PB,                     /* the jobs array of a sequence */
    NULL_PTR,                          /* sequence end notify callack */
    (uint8)FALSE                     /* Interruptible */
};

/* Sequence Configuration of SpiSequence_2_Spi5_Slave */
SPI_DATA_SECTION static const Spi_SeqCfgType Spi_SequenceConfig_SpiSequence_2_Spi5_Slave =
{
    /* SpiSequence_2_Spi5_Slave */
    (Spi_JobType)1u,
    SPI_SPURIOUS_CORE_ID_U32,
    SpiSequence_2_Spi5_Slave_JobsArray_PB,                     /* the jobs array of a sequence */
    NULL_PTR,                          /* sequence end notify callack */
    (uint8)FALSE                     /* Interruptible */
};

/* Spi_apSequenceConfigList Sequence Configuration of Spi*/
SPI_DATA_SECTION static const Spi_SeqsCfgType Spi_aSequenceConfigList[3] =
{
    /* SpiSequence_0_Spi_Flash */
    {
        &Spi_SequenceConfig_SpiSequence_0_Spi_Flash
    },

    /* SpiSequence_1_Spi2_Master */
    {
        &Spi_SequenceConfig_SpiSequence_1_Spi2_Master
    },

    /* SpiSequence_2_Spi5_Slave */
    {
        &Spi_SequenceConfig_SpiSequence_2_Spi5_Slave
    }
};





/* FCSpiChannelAttributesConfig_PB Channel Attribute Configuration of SpiChannel_0*/
SPI_DATA_SECTION static const Spi_ChnlAttrsType Spi_ChnlAttrsConfig_SpiChannel_0 =
{
    SPI_SPURIOUS_CORE_ID_U32,
    (uint32)(FCSPI_TRCTRL_MSB_U32 | FCSPI_TRCTRL_WIDTH_1_U32 | ((uint32)(7))),            /* Channel attribution on TCR register */
    (uint32)(((uint32)(0) << 16) | ((uint32)(3))),                                        /* FIFO Watermark */
    SPI_DATA_RW_8_BITS_PER_UNIT                                                          /* u8DataWidth */
};

/* FCSpiChannelAttributesConfig_PB Channel Attribute Configuration of SpiChannel_1*/
SPI_DATA_SECTION static const Spi_ChnlAttrsType Spi_ChnlAttrsConfig_SpiChannel_1 =
{
    SPI_SPURIOUS_CORE_ID_U32,
    (uint32)(FCSPI_TRCTRL_MSB_U32 | FCSPI_TRCTRL_WIDTH_1_U32 | ((uint32)(7))),            /* Channel attribution on TCR register */
    (uint32)(((uint32)(0) << 16) | ((uint32)(3))),                                        /* FIFO Watermark */
    SPI_DATA_RW_8_BITS_PER_UNIT                                                          /* u8DataWidth */
};

/* FCSpiChannelAttributesConfig_PB Channel Attribute Configuration of SpiChannel_2*/
SPI_DATA_SECTION static const Spi_ChnlAttrsType Spi_ChnlAttrsConfig_SpiChannel_2 =
{
    SPI_SPURIOUS_CORE_ID_U32,
    (uint32)(FCSPI_TRCTRL_MSB_U32 | FCSPI_TRCTRL_WIDTH_1_U32 | ((uint32)(15))),            /* Channel attribution on TCR register */
    (uint32)(((uint32)(0) << 16) | ((uint32)(3))),                                        /* FIFO Watermark */
    SPI_DATA_RW_16_BITS_PER_UNIT                                                         /* u8DataWidth */
};

/* FCSpiChannelAttributesConfig_PB Channel Attribute Configuration of SpiChannel_3*/
SPI_DATA_SECTION static const Spi_ChnlAttrsType Spi_ChnlAttrsConfig_SpiChannel_3 =
{
    SPI_SPURIOUS_CORE_ID_U32,
    (uint32)(FCSPI_TRCTRL_MSB_U32 | FCSPI_TRCTRL_WIDTH_1_U32 | ((uint32)(15))),            /* Channel attribution on TCR register */
    (uint32)(((uint32)(0) << 16) | ((uint32)(3))),                                        /* FIFO Watermark */
    SPI_DATA_RW_16_BITS_PER_UNIT                                                         /* u8DataWidth */
};

/* Spi_aChnlAttrsConfigList_ Job Configuration of Spi*/
SPI_DATA_SECTION static const Spi_ChannelsAttrsType Spi_aChnlAttrsConfigList[4] =
{
    /* SpiChannel_0 */
    {
        &Spi_ChnlAttrsConfig_SpiChannel_0
    },

    /* SpiChannel_1 */
    {
        &Spi_ChnlAttrsConfig_SpiChannel_1
    },

    /* SpiChannel_2 */
    {
        &Spi_ChnlAttrsConfig_SpiChannel_2
    },

    /* SpiChannel_3 */
    {
        &Spi_ChnlAttrsConfig_SpiChannel_3
    }
};




/* Array of FCSpi Unit configurations SpiHwUnit_0_Flash */
SPI_DATA_SECTION static const Spi_HwUnitCfgType Spi_HwUnitConfig_SpiHwUnit_0_Flash =
{
    FCSPI_1_OFFSET,
    SPI_SPURIOUS_CORE_ID_U32,                   /* SpiCoreUse */
    SPI_MASTER,
    SPI_HW_UNIT_SYNC_U8
#if ((SPI_ASYNC_DRIVER == STD_ON) && (SPI_DMA_USED == STD_ON))
    ,FALSE
    ,0u
    ,0u
    ,DMA_INSTANCE_MAX
#endif
};

/* Array of FCSpi Unit configurations SpiHwUnit_1 */
SPI_DATA_SECTION static const Spi_HwUnitCfgType Spi_HwUnitConfig_SpiHwUnit_1 =
{
    FCSPI_2_OFFSET,
    SPI_SPURIOUS_CORE_ID_U32,                   /* SpiCoreUse */
    SPI_MASTER,
    SPI_HW_UNIT_ASYNC_U8
#if ((SPI_ASYNC_DRIVER == STD_ON) && (SPI_DMA_USED == STD_ON))
    ,FALSE
    ,0u
    ,0u
    ,DMA_INSTANCE_MAX
#endif
};

/* Array of FCSpi Unit configurations SpiHwUnit_2 */
SPI_DATA_SECTION static const Spi_HwUnitCfgType Spi_HwUnitConfig_SpiHwUnit_2 =
{
    FCSPI_5_OFFSET,
    SPI_SPURIOUS_CORE_ID_U32,                   /* SpiCoreUse */
    SPI_SLAVE,
    SPI_HW_UNIT_ASYNC_U8
#if ((SPI_ASYNC_DRIVER == STD_ON) && (SPI_DMA_USED == STD_ON))
    ,TRUE                       /* DMA used or not */
    ,1u                               /* FCSPI_5 Tx DMA channel */
    ,2u                               /* FCSPI_5 Rx DMA channel */
    ,DMA_INSTANCE_0                               /* FCSPI_5 Dma Instance */
#endif
};

/* Array of Hardware Unit configurations */
SPI_DATA_SECTION static const Spi_HwUnitsConfigType Spi_aHwUnitConfigList[3U] =
{
    /* SpiHwUnit_0_Flash */
    {
    &Spi_HwUnitConfig_SpiHwUnit_0_Flash
    },

    /* SpiHwUnit_1 */
    {
    &Spi_HwUnitConfig_SpiHwUnit_1
    },

    /* SpiHwUnit_2 */
    {
    &Spi_HwUnitConfig_SpiHwUnit_2
    }
};


/*==================================================================================================
*                                      GLOBAL CONSTANTS
==================================================================================================*/



/* @violates @ref Spi_PBcfg_c_REF_4 MISRA 2004 Required Rule 8.10, external linkage ... */
/* MODULE-CONFIGURATION Configuration */
SPI_DATA_SECTION const Spi_ConfigType Spi_Config=
{
    3u,                                  /* Number of external devices */
    3u,                                  /* Number of channels */
    2u,                                  /* Number of jobs */
    2u,                                  /* Number of sequences */
    SPI_SPURIOUS_CORE_ID_U32,                                   /* SpiCoreUse */
    Spi_aChannelConfigList,              /* pcChannelConfig */
    Spi_aJobConfigList,                  /* pcJobConfig */
    Spi_aSequenceConfigList,             /* pcSequenceConfig */
    Spi_aChnlAttrsConfigList,            /* pcChannelsAttrConfig */
    Spi_aExternalDeviceConfigList,       /* pcExternalDeviceConfig */
    Spi_aHwUnitConfigList                /* pcHWUnitConfig */
    /**
    * @brief   DEM error parameters
    */
#if (SPI_DEM_ENABLE == STD_ON)
    ,{ (uint32)STD_OFF, (uint32)0U} /* SPI_E_HARDWARE_ERROR parameters*/
    ,{ (uint32)STD_OFF, (uint32)0U} /* SPI_E_TIMEOUT_ERROR parameters*/
#endif /* SPI_DEM_ENABLE == STD_ON */
};



#define SPI_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "Spi_MemMap.h"

#ifdef __cplusplus
}
#endif

/** @} */

