/**
*   @file         Ocu_Cfg.h
*
*   @addtogroup   ocu_driver Ocu Driver
*   @brief        Ocu HLD Precompile configuration header file
*   @details      Precompile parameters and extern configuration.
*
*   @{
*/
/*==================================================================================================
*   PERIPHERAL           : FTU
*   PLATFORM             : Flagchip FC7300
*   AUTOSAR VERSION      : 4.6.0
*   AUTOSAR REVISION     : ASR_REL_4_6_0
*   SOFTWARE VERSION     : 1.5.1
*   VENDOR               : Flagchip Semiconductors
*
*   Copyright 2020-2024 Flagchip Semiconductors Co., Ltd.
*   All Rights Reserved.
==================================================================================================*/
#ifndef OCU_CFG_H
#define OCU_CFG_H

#ifdef __cplusplus
extern "C" {
#endif

/*==================================================================================================
*                                         INCLUDE FILES
==================================================================================================*/

/*==================================================================================================
*                               SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define OCU_CFG_VENDOR_ID                         174
#define OCU_CFG_MODULE_ID                         125
#define OCU_CFG_AR_RELEASE_MAJOR_VERSION          4
#define OCU_CFG_AR_RELEASE_MINOR_VERSION          6
#define OCU_CFG_AR_RELEASE_REVISION_VERSION       0
#define OCU_CFG_SW_MAJOR_VERSION                  1
#define OCU_CFG_SW_MINOR_VERSION                  5
#define OCU_CFG_SW_PATCH_VERSION                  1

/*==================================================================================================
*                                           CONSTANTS
==================================================================================================*/

/*==================================================================================================
*                                       DEFINES AND MACROS
==================================================================================================*/

/**
 * @brief Enable/disable support for mutilcore feature. 
 * 
 */
#define OCU_MULTICORE_SUPPORT           (STD_ON)

#if (STD_ON == OCU_MULTICORE_SUPPORT)
    #define Ocu_GetCoreID()             (GET_CPU_ID())
#else
    #define Ocu_GetCoreID()             (0U)
#endif

/** @brief    Maximum number of configured partitions. */
#define OCU_MAX_PARTITIONS              (2U)

/**
 * @brief Switch to indicate that Ocu_DeInit API is supported
 *
 */
#define OCU_DEINIT_API                  (STD_ON)

/**
 * @brief Switch to indicate that Ocu_SetPinState API is supported
 *
 */
#define OCU_SET_PIN_STATE_API           (STD_ON)

/**
 * @brief Switch to indicate that Ocu_SetPinAction API is supported
 *
 */
#define OCU_SET_PIN_ACTION_API          (STD_ON)

/**
 * @brief Switch to indicate that Ocu_GetCounter API is supported
 *
 */
#define OCU_GET_COUNTER_API             (STD_ON)

/**
 * @brief Switch to indicate that Ocu_GetVersionInfo API is supported
 * 
 */
#define OCU_VERSION_INFO_API            (STD_ON)

/**
 * @brief Switch to indicate that Ocu_SetAbsoluteThreshold API is supported
 *
 */
#define OCU_SET_ABSOLUTE_THRESHOLD_API  (STD_ON)

/**
 * @brief Switch to indicate that Ocu_SetRelativeThreshold API is supported
 *
 */
#define OCU_SET_RELATIVE_THRESHOLD_API  (STD_ON)

/**
 * @brief Switch to indicate that the notifications are supported
 *
 */
#define OCU_NOTIFICATION_SUPPORTED      (STD_ON)

/**
 * @brief Switch to indicate that the down counting is supported
 *
 */
#define OCU_DOWNCOUNTING_SUPPORTED      (STD_OFF)

/**
 * @brief Switch for enabling the development error detection.
 *
 */
#define OCU_DEV_ERROR_DETECT            (STD_ON)

/**
 * @brief Whether OCU have TPU hardware module.
 *
 */
#define OCU_HAVE_TPU                    (STD_OFF)

/**
 * @brief Whether OCU have EFTU hardware module.
 *
 */
#define OCU_HAVE_EFTU                   (STD_ON)

/**
 * @brief Switch for enabling the runtime error detection.
 *
 */
#define OCU_DISABLE_DET_RUNTIME_REPORT_ERROR_STATUS (STD_OFF)


#define  OCU_PRECOMPILE_SUPPORT         (STD_OFF)

/* PRQA S 0791 ++ #Misra-C:2012 Rule-5.4 Macro identifiers shall be distinct
 * Reason: There are some marcos generated by configuration tool which used by user, so, this macros may not distinct */
/** 
 * @brief Symbolic Names for configured channels
 */
#define  OcuConf_OcuChannel_OcuChannel_0         ((Ocu_ChannelType)0U)
#define  OcuConf_OcuChannel_OcuChannel_1         ((Ocu_ChannelType)1U)
#define  OcuConf_OcuChannel_OcuChannel_2         ((Ocu_ChannelType)2U)
/* PRQA S 0791 -- */

/**
 * @brief OCU FTU driver and interrupt used
 */
#define OCU_FTU_0_USED
#define OCU_FTU_0_ISR_USED
#define OCU_FTU_3_USED
#define OCU_FTU_3_ISR_USED

/**
 * @brief OCU EFTU driver and interrupt used
 */
#define OCU_EFTU0_TOM_0_7_ISR_USED

/** @brief maximum of OCU channels on this platform */
#define OCU_MAX_CHANNELS            (3U)

/** @brief maximum of FTU channels on this platform */
#define OCU_FTU_HW_CHANNEL_MAX      (2U)

/** @brief maximum of FTU modules on this platform */
#define OCU_FTU_HW_MODULES          (6U)

/** @brief maximum of FTU channels per module on this platform */
#define OCU_FTU_CH_PER_MODULES      (8U)

/** @brief maximum of FTU channels on this platform */
#define OCU_FTU_HW_CHANNELS         (OCU_FTU_HW_MODULES * OCU_FTU_CH_PER_MODULES)

/** @brief Each module has 8 channel slots */
#define OCU_FTU_MODULE_CHANNELS_NO  (8U)

/** @brief maximum of TPU channels on this platform */
#define OCU_TPU_HW_CHANNEL_MAX      (0U)

/** @brief maximum of TPU modules on this platform */
#define OCU_TPU_HW_MODULES          (0U)

/** @brief maximum of TPU channels per module on this platform */
#define OCU_TPU_CH_PER_MODULES      (0U)

/** @brief maximum of TPU channels on this platform */
#define OCU_TPU_HW_CHANNELS         (OCU_TPU_HW_MODULES * OCU_TPU_CH_PER_MODULES)

/** @brief maximum of eFTU channels on this platform */
#define OCU_EFTU_HW_CHANNEL_MAX     (1U)

/** @brief maximum of eFTU modules on this platform */
#define OCU_EFTU_HW_MODULES         (2U)

/** @brief maximum of eFTU channels per module on this platform */
#define OCU_TOM_CH_PER_MODULES      (8U)

/** @brief maximum of eFTU channels on this platform */
#define OCU_EFTU_HW_CHANNELS        (OCU_EFTU_HW_MODULES * OCU_TOM_CH_PER_MODULES)

/** @brief Defines the maximum number of hw channels in the current configuration */
#define  OCU_HW_CHANNELS_NO         (OCU_FTU_HW_CHANNELS + OCU_TPU_HW_CHANNELS + OCU_EFTU_HW_CHANNELS)

/*==================================================================================================
*                                       GLOBAL CONSTANTS
==================================================================================================*/
#define OCU_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "Ocu_MemMap.h"

#define OCU_CONF_PB \
 extern const Ocu_ConfigType Ocu_Config;

#define OCU_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "Ocu_MemMap.h"
/*==================================================================================================
*                                              ENUMS
==================================================================================================*/


/*==================================================================================================
*                                  STRUCTURES AND OTHER TYPEDEFS
==================================================================================================*/
typedef uint32 Ocu_ValueType;

#ifdef __cplusplus
}
#endif

#endif    /*OCU_CFG_H*/

/** @} */

