/**
*   @file    Spi_Cfg.h
*   @version 1.5.1
*
*   @brief   AUTOSAR Spi - Module configuration interface for Spi driver.
*   @details Contains the module configuration interface for Spi driver.
*
*   @addtogroup SPI
*   @{
*/
/*==================================================================================================
*   PERIPHERAL           : Spi
*   PLATFORM             : Flagchip FC7300
*   AUTOSAR VERSION      : 4.6.0
*   AUTOSAR REVISION     : ASR_REL_4_6_0
*   SOFTWARE VERSION     : 1.5.1
*   VENDOR               : Flagchip Semiconductors
*
*   Copyright 2020-2023 Flagchip Semiconductors Co., Ltd.
*   All Rights Reserved.
==================================================================================================*/
/*==================================================================================================
*   Revision History:
*
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------- ----------   ---------------
*   0.1.0       14/07/2023    QXW0071       N/A          SPI Initial Version
*   0.2.0       03/10/2023    QXW0071       N/A          Add support for multi-core
*   0.3.0       19/10/2023    QXW0071       N/A          Optimize code to comply with Misra-C rules
*   0.4.0       17/11/2023    QXW0071       N/A          Add workaround when enable CS Continuous and sample on first edge.
*   0.5.0       01/16/2024    QXW0071       N/A          Optimize Code
*   0.6.0       02/28/2024    QXW0103       N/A          Add support for FC7240
==================================================================================================*/

#ifndef SPI_CFG_H
#define SPI_CFG_H

#ifdef __cplusplus
extern "C"{
#endif

/*==================================================================================================
*                                        INCLUDE FILES
==================================================================================================*/
#include "Std_Types.h"

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
/* PRQA S 0791 ++ #Misra-C:2012 Rule-5.4 Macro identifiers shall be distinct 
 * Reason: There are some marcos generated by configuration tool which used by user, so, this macros may not distinct */
#define SPI_CFG_AR_RELEASE_MAJOR_VERSION        4U
#define SPI_CFG_AR_RELEASE_MINOR_VERSION        6U
#define SPI_CFG_AR_RELEASE_REVISION_VERSION     0U
#define SPI_CFG_SW_MAJOR_VERSION                1U
#define SPI_CFG_SW_MINOR_VERSION                5U
#define SPI_CFG_SW_PATCH_VERSION                1U
#define SPI_CFG_MODULE_ID                       83U
#define SPI_CFG_VENDOR_ID                       174U

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/

/*==================================================================================================
*                                          CONSTANTS
==================================================================================================*/

/**
* @brief Total number of partitions configured in Ecu.
*/
#define SPI_MAX_PARTITIONS             (2U)

/**
* @brief          Enable Multicore Support.
* @details        When SpiGeneral/SpiMulticoreSupport = TRUE,
*                 the SPI driver can be configured to support multicore.
*/
#define SPI_MULTICORE_ENABLED          (STD_ON)

#if (STD_OFF == SPI_MULTICORE_ENABLED)
/**
* @brief Defines default CodeId value which is assigned to HWUnits, Sequences, Jobs and Channels in the case multicore is not enabled.
*/
#define SPI_SPURIOUS_CORE_ID_U32        ((uint32)0UL)
#endif

/**
* @brief Switches the Development Error functionality ON or OFF.
* @details Switches the Development Error Detection and Notification ON or OFF.
* @implements SPI_DEV_ERROR_DETECT_define
*/
#define SPI_DET_ENABLE           (STD_ON)

/**
* @brief Switches the Version Information API functionality ON or OFF.
* @details Switches the Spi_GetVersionInfo function ON or OFF.
*/
#define SPI_GET_VERSION_INFO_API_SUPPORT           (STD_ON)

/**
* @brief Switches the Interruptible Sequences handling functionality ON or OFF.
* @details This parameter depends on SPI_LEVEL_DELIVERED value.
*        It is only used for SPI_LEVEL_DELIVERED configured to 1 or 2.
* @implements SPI_INTERRUPTIBLE_SEQ_ALLOWED_define
*/
#define SPI_INTERRUPTIBLE_SEQ_ALLOWED  (STD_OFF)

/**
* @brief Switches the Spi_GetHWUnitStatus function ON or OFF.
* @details Switches the Spi_GetHWUnitStatus function ON or OFF.
* @implements SPI_HW_STATUS_API_define
*/
#define SPI_HW_STATUS_API          (STD_ON)

/**
* @brief Switches the Spi_Cancel function ON or OFF.
* @details Switches the Spi_Cancel function ON or OFF. (see chapter 8.3.13)
* @implements SPI_CANCEL_API_define
*/
#define SPI_CANCEL_API             (STD_ON)

/* PRQA S 791 ++ #Misra-C:2012 Rule-5.4 Macro identifiers shall be distinct 
 * Reason: These macros have the same first 30 characters,but they are differrent in follow characters.Modern compiler will recognize the difference. */

/* Usage 0: the SPI Handler/Driver manages only Internal Buffers */
#define SPI_CHANNEL_BUFFER_TYPE_FLAG_ONLY_IB          0u

/* Usage 1: the SPI Handler/Driver manages only External Buffers */
#define SPI_CHANNEL_BUFFER_TYPE_FLAG_ONLY_EB          1u
/* PRQA S 791 -- */

/* Usage 2: the SPI Handler/Driver manages both buffers types. */
#define SPI_CHANNEL_BUFFER_TYPE_FLAG_IB_EB_BOTH       2u

/**
* @brief Selects the SPI Handler Driver Channel Buffers usage allowed and delivered.
* @details Selects the SPI Handler Driver Channel Buffers usage allowed and delivered.
*        (see chapter 7.2.1)
* @implements SPI_CHANNEL_BUFFERS_ALLOWED_define
*/
#define SPI_CHANNEL_BUFFERS_ALLOWED    (SPI_CHANNEL_BUFFER_TYPE_FLAG_IB_EB_BOTH)


#define SPI_CHANNEL_IB_ALLOWED  STD_ON

#define SPI_CHANNEL_EB_ALLOWED  STD_ON

/* The LEVEL 0 Simple Synchronous SPI Handler Driver functionalities are selected.*/
#define SPI_LEVEL_0                          0x00u

/* The LEVEL 1 Basic Asynchronous SPI Handler Driver functionalities are selected.*/
#define SPI_LEVEL_1                          0x01u

/* The LEVEL 2 Enhanced SPI Handler Driver functionalities are selected. */
#define SPI_LEVEL_2                          0x02u

/**
* @brief Selects the SPI Handler Driver level of scalable functionality.
* @details Selects the SPI Handler Driver level of scalable functionality that
* is available and delivered. (see chapter 7.1)
* @implements SPI_LEVEL_DELIVERED_define
*/
#define SPI_LEVEL_DELIVERED            (SPI_LEVEL_2)

#define SPI_ASYNC_DRIVER      (STD_ON)

#define SPI_SYNC_DRIVER      (STD_ON)


#define SpiConf_SpiChannel_SpiChannel_0    ((Spi_ChannelType)0)
#define SpiConf_SpiChannel_SpiChannel_1    ((Spi_ChannelType)1)
#define SpiConf_SpiChannel_SpiChannel_2    ((Spi_ChannelType)2)
/**
* @brief Defines the maximum number of supported channels.
* @details Defines the maximum number of supported channels
*     for all the driver configurations.
*/
#define SPI_CHANNEL_MAX_COUNT  (3u)


#define SpiConf_SpiJob_SpiJob_0   ((Spi_JobType)0)
#define SpiConf_SpiJob_SpiJob_1_Flash   ((Spi_JobType)1)

/**
* @brief Total number of Jobs configured.
* @details Defines the maximum number of supported jobs
*     for all the driver configurations.
*/
#define SPI_JOB_MAX_COUNT     (2u)


#define SpiConf_SpiSequence_SpiSequence_0   ((Spi_SequenceType)0)
#define SpiConf_SpiSequence_SpiSequence_1_Flash_SPI2   ((Spi_SequenceType)1)

/**
* @brief Total number of Sequences configured.
* @details Defines the maximum number of supported sequences
*     for all the driver configurations.
*/
#define SPI_SEQUENCE_MAX_COUNT  (2u)

/**
* @brief Defines the peripherals used throughout the configuration(s).
* @details Defines the peripherals used throughout the configuration(s).
*/
#define CSIB0  ((uint8)0u)
#define CSIB1  ((uint8)1u)
#define SPI_HW_MODULE_MAX_COUNT   (2u)

/**
* @brief Physical HWUnits definition - as from resource manager.
* @details Physical HWUnits definition - as from resource manager.
*/
#define FCSPI_3_HWUNIT   (CSIB0)

#define FCSPI_2_HWUNIT   (CSIB1)


/**
 * @brief        Peripheral SPI0 base address
 */
#define FCSPI0_BASEADDR                            (0x40062000U)

/**
 * @brief        Peripheral SPI1 base address
 */
#define FCSPI1_BASEADDR                            (0x40063000U)

/**
 * @brief        Peripheral SPI2 base address
 */
#define FCSPI2_BASEADDR                            (0x40064000U)

/**
 * @brief        Peripheral SPI3 base address
 */
#define FCSPI3_BASEADDR                            (0x40065000U)

/**
 * @brief        Peripheral SPI4 base address
 */
#define FCSPI4_BASEADDR                            (0x40470000U)

/**
 * @brief        Peripheral SPI5 base address
 */
#define FCSPI5_BASEADDR                            (0x40471000U)

/**
 * @brief        Peripheral SPI6 base address
 */
#define FCSPI6_BASEADDR                             (0U)

/**
 * @brief        Peripheral SPI7 base address
 */
#define FCSPI7_BASEADDR                             (0U)


/**
* @brief Physical HWUnits enabled/disabled
* @details Physical HWUnits enabled/disabled
*/
#define FCSPI_0_ENABLED  (STD_OFF)
#define FCSPI_1_ENABLED  (STD_OFF)
#define FCSPI_2_ENABLED  (STD_ON)
#define FCSPI_3_ENABLED  (STD_ON)
#define FCSPI_4_ENABLED  (STD_OFF)
#define FCSPI_5_ENABLED  (STD_OFF)
#define FCSPI_6_ENABLED  (STD_OFF)
#define FCSPI_7_ENABLED  (STD_OFF)

#define SPI_MODE_SYNC   0u
#define SPI_MODE_ASYNC_FIFO   1u
#define SPI_MODE_ASYNC_DMA   2u

#define FCSPI_3_MODE   SPI_MODE_ASYNC_FIFO
#define FCSPI_2_MODE   SPI_MODE_SYNC

#define SPI_SLAVE_MODE_SUPPORT  ((STD_OFF))



#define FCSPI_2_OFFSET  2u

#define FCSPI_3_OFFSET  3u






/**
* @brief Defines the external devices the driver will use.
* @details Reference to the external device used by this job.
*/
#define SPI_Slave_of_Spi3  ((Spi_ExternalDeviceType)0u)
#define SPI_SPI_Flash_GD25Q32  ((Spi_ExternalDeviceType)1u)



/**
* @brief   Switches the Production Error Detection and Notification OFF
*
* @implements SPI_DEM_ENABLE define
* STD_OFF: Enable Production Error Detection - STD_ON: Disable Production Error Detection
*/
#define SPI_DEM_ENABLE   (STD_OFF )

#define SPI_SUP_CONT_EN_SECOND_EDGE_SAMPLE      (STD_ON)
/*==================================================================================================
 *                                     DEFINES AND MACROS
==================================================================================================*/
/**
* @brief Define values for Autosar configuration variants.
* @details Define values for Autosar configuration variants.
*/
#define SPI_VARIANT_PRECOMPILE  (0)
#define SPI_VARIANT_POSTBUILD   (1)
#define SPI_VARIANT_LINKTIME    (2)

/**
* @brief Defines the use of Post-Build(PB) support.
* @details VARIANT-POST-BUILD: Parameters with "Pre-compile time",
*        "Link time" and "Post-build time" are allowed in this variant.
*/
/* Post-Build(PB) Support. */
/**
* @implements SPI_CONFIG_VARIANT_define
*/

#define SPI_CONFIG_VARIANT      (SPI_VARIANT_POSTBUILD)

/*
* @violates @ref Spi_Cfg_h_REF_3 Precautions shall be taken in order for
* defines not leading to unexpected behaviour when substitution is made.
*/
    #define SPI_CONF_PB \
 extern const Spi_ConfigType Spi_Config_EcucPartition_0; \
 extern const Spi_ConfigType Spi_Config_EcucPartition_1; \

/**
* @brief Define precompile support.
* @details Define precompile support if VariantPreCompile or VariantLinkTime is selected and number of variant <=1.
*/
/*
* @violates @ref Spi_Cfg_h_REF_1 A project should not contain unused macro declarations.
* Macros that are used in the code only in some configuration.
*/

#define SPI_PRECOMPILE_SUPPORT      (STD_OFF)

/**
* @brief Defines if transfers are made using DMA or FIFO.
* @details Defines if transfers are made using DMA or FIFO.
* @implements SPI_DMA_USED_define
*/
/*
* @violates @ref Spi_Cfg_h_REF_1 A project should not contain unused macro declarations.
* Macros that are used in the code only in some configuration.
*/

#define SPI_DMA_USED     (STD_ON)

/**
* @brief Number of CPU clock cycles consumed by a wait loop during the wait for TX/RX transmission to complete one frame in Spi_SyncTransmit().
* @details This value is set to the minimum measure retrieved for GHS, DIAB and CW compilers,
*       with all optimizations activated.
*/
#define SPI_WAIT_LOOP_TICKS       23u

/**
* @brief Defines the "Number of Loops" timeout.
* @details Defines the "Number of Loops" timeout used by Spi_SyncTransmit and Spi_AsyncTransmit
*        function during the wait on TX/RX transmission to complete one frame.
*        One timeout unit means that no TX or RX was executed(the IF statements are returning FALSE).
*/

#define SPI_TIMEOUT_COUNTER       ((sint32)((15000000u) / SPI_WAIT_LOOP_TICKS))

/**
* @brief Allow simultaneous calls to Spi_SyncTransmit() for different threads.
* @details Two concurrent calls to Spi_SyncTransmit() will be allowed only if the related sequences
*       do not share HW units.
*/
#define SPI_SUPPORT_CONCURRENT_SYNC_TRANSMIT    (STD_OFF)

/*==================================================================================================
 *                                           Non AUTOSAR DEFINES
==================================================================================================*/
/**
* @brief If enabled, the asyncronous operation mode (POLLING or INTERRUPT)
* @details If enabled, the asyncronous operation mode (POLLING or INTERRUPT) can
*       be defined independently for each spi hardware module using SPI_SetHwAsyncMode().
* @implements SPI_HWUNIT_ASYNC_MODE_define
*/
#define SPI_HWUNIT_ASYNC_MODE  (STD_ON)


/**
* @brief If this enabled, support more than 256 sequences, jobs and channels.
*/
#define SPI_MORE_THAN_256_SEQ_JOB_CHAN_SUPPORT (STD_ON)

/**
* @brief define the bit count of read from/write to memory per time
*/
#define SPI_DATA_RW_8_BITS_PER_UNIT  ((uint8)1)
#define SPI_DATA_RW_16_BITS_PER_UNIT ((uint8)2)
#define SPI_DATA_RW_32_BITS_PER_UNIT ((uint8)4)

/* PRQA S 0791 -- */
/*==================================================================================================
*                                            ENUMS
==================================================================================================*/


/*==================================================================================================
*                               STRUCTURES AND OTHER TYPEDEFS
==================================================================================================*/


/*==================================================================================================
*                                GLOBAL VARIABLE DECLARATIONS
==================================================================================================*/

/*==================================================================================================
*                                    FUNCTION PROTOTYPES
==================================================================================================*/


#ifdef __cplusplus
}
#endif

#endif /*SPI_CFG_H*/

/** @} */
