/**
*   @file    Spi_PBcfg.c
*   @version 1.5.1
*
*   @brief   AUTOSAR Spi - Post Build configuration Spi source file.
*   @details Post Build configuration file for Spi driver.
*
*   @addtogroup SPI
*   @{
*/
/*==================================================================================================
*   PERIPHERAL           : SPI
*   PLATFORM             : Flagchip FC7300
*   AUTOSAR VERSION      : 4.6.0
*   AUTOSAR REVISION     : ASR_REL_4_6_0
*   SOFTWARE VERSION     : 1.5.1
*   VENDOR               : Flagchip Semiconductors
*
*   Copyright 2020-2023 Flagchip Semiconductors Co., Ltd.
*   All Rights Reserved.
==================================================================================================*/
/*==================================================================================================
*   Revision History:
*
*   Version     Date          Initials      CR#          Descriptions
*   ---------   ----------    ------------- ----------   ---------------
*   0.1.0       14/07/2023    QXW0071       N/A          SPI Initial Version
*   0.2.0       03/10/2023    QXW0071       N/A          Add support for multi-core
*   0.3.0       19/10/2023    QXW0071       N/A          Optimize code to comply with Misra-C rules
*   0.4.0       17/11/2023    QXW0071       N/A          Add workaround when enable CS Continuous and sample on first edge.
*   0.5.0       01/16/2024    QXW0071       N/A          Optimize Code
*   0.6.0       02/28/2024    QXW0103       N/A          Add support for FC7240
==================================================================================================*/

#ifdef __cplusplus
extern "C"{
#endif
/* PRQA S 0791 EOF 
   0791:Macro identifier does not differ from other macro identifier(s) (e.g. '%1s') within the 
	specified number of significant characters.
   REASON:These macros have the same first 30 characters,but they are differrent in follow characters.Modern compiler will recognize the difference.
*/

/* PRQA S 0779 ++ #Misra-C:2012 Rule-5.2 Identifiers declared in the same scope and name space
*  shall be distinct
*  0779:Identifier does not differ from other identifier(s) within the specified number of
*  significant characters.
*  REASON:These identifiers are automatically generated by configuration tool, and they are
*  distinct.
*/

/* PRQA S 3678 EOF #Misra-C:2012 Rule-8.13 A pointer should point to a const-qualified type whenever possible
 * Reason: That object can not be declared with const type */
/*==================================================================================================
*                                        INCLUDE FILES
==================================================================================================*/

#include "Spi.h"
#include "Spi_RegOps.h"

#if (SPI_DEM_ENABLE == STD_ON)
#include "Dem.h"
#endif /* SPI_DEM_ENABLE == STD_ON */

/*==================================================================================================
*                                    SOURCE FILE VERSION INFORMATION
==================================================================================================*/

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/


/*==================================================================================================
*                                      GLOBAL FUNCTIONS
==================================================================================================*/
#define SPI_START_SEC_CODE
#include "Spi_MemMap.h"



#define SPI_STOP_SEC_CODE
#include "Spi_MemMap.h"

/*==================================================================================================
*                                      LOCAL VARIABLES
==================================================================================================*/
#if ((SPI_DMA_USED == STD_ON) && (SPI_ASYNC_DRIVER == STD_ON))
    #define SPI_START_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
#else
    #define SPI_START_SEC_VAR_NO_INIT_UNSPECIFIED
#endif /* ((SPI_DMA_USED == STD_ON) && (SPI_ASYNC_DRIVER == STD_ON)) */
#include "Spi_MemMap.h"



/*  Buffers Descriptors for EB Channels (if any) */
/* Allocate Buffers for IB Channels (if any) */
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferTX_PBSpiChannel_0[4], 4)
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferRX_PBSpiChannel_0[4], 4)
/* Allocate Buffers for IB Channels (if any) */
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferTX_PBSpiChannel_1[4], 4)
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferRX_PBSpiChannel_1[4], 4)
/* Allocate Buffers for IB Channels (if any) */
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferTX_PBSpiChannel_2[2], 4)
SPI_DATA_SECTION VAR_ALIGN(static Spi_DataBufferType BufferRX_PBSpiChannel_2[2], 4)


#if ((SPI_DMA_USED == STD_ON) && (SPI_ASYNC_DRIVER == STD_ON))
    #define SPI_STOP_SEC_VAR_NO_INIT_UNSPECIFIED_NO_CACHEABLE
#else
    #define SPI_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#endif /* ((SPI_DMA_USED == STD_ON) && (SPI_ASYNC_DRIVER == STD_ON)) */
#include "Spi_MemMap.h"

#define SPI_START_SEC_VAR_INIT_UNSPECIFIED
#include "Spi_MemMap.h"



/*  Buffers Descriptors for IB Channels (if any) */
SPI_DATA_SECTION static Spi_ChannelbufferType Buffer_PBSpiChannel_0 =
{
    BufferTX_PBSpiChannel_0,
    BufferRX_PBSpiChannel_0
};
SPI_DATA_SECTION static Spi_ChannelbufferType Buffer_PBSpiChannel_1 =
{
    BufferTX_PBSpiChannel_1,
    BufferRX_PBSpiChannel_1
};
SPI_DATA_SECTION static Spi_ChannelbufferType Buffer_PBSpiChannel_2 =
{
    BufferTX_PBSpiChannel_2,
    BufferRX_PBSpiChannel_2
};


#define SPI_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "Spi_MemMap.h"

/*==================================================================================================
*                                      LOCAL CONSTANTS
==================================================================================================*/

#define SPI_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "Spi_MemMap.h"




/* SpiChannelConfig_PB Channel Configuration of SpiChannel_0*/
SPI_DATA_SECTION static const Spi_ChnlCfgType Spi_ChannelConfig_SpiChannel_0 =
{
    /* SpiChannel_0*/
    IB,
    (uint32)0x55u,
    4U,
    &Buffer_PBSpiChannel_0,
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aChnlStats[0]
};

/* SpiChannelConfig_PB Channel Configuration of SpiChannel_1*/
SPI_DATA_SECTION static const Spi_ChnlCfgType Spi_ChannelConfig_SpiChannel_1 =
{
    /* SpiChannel_1*/
    IB,
    (uint32)0x55u,
    4U,
    &Buffer_PBSpiChannel_1,
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aChnlStats[1]
};

/* SpiChannelConfig_PB Channel Configuration of SpiChannel_2*/
SPI_DATA_SECTION static const Spi_ChnlCfgType Spi_ChannelConfig_SpiChannel_2 =
{
    /* SpiChannel_2*/
    IB,
    (uint32)0U,
    2U,
    &Buffer_PBSpiChannel_2,
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aChnlStats[2]
};

/* Spi_apChannelConfigList Channel Configuration of Spi*/
SPI_DATA_SECTION static const Spi_ChannelsCfgType Spi_aChannelConfigList[3] =
{
    /* SpiChannel_0 */
    {
        &Spi_ChannelConfig_SpiChannel_0
    },

    /* SpiChannel_1 */
    {
        &Spi_ChannelConfig_SpiChannel_1
    },

    /* SpiChannel_2 */
    {
        &Spi_ChannelConfig_SpiChannel_2
    }
};




/* Channel to Job Assignment */

SPI_DATA_SECTION static const Spi_ChannelType SpiJob_0_ChnlsArray_PB[1] = {SpiConf_SpiChannel_SpiChannel_0};
SPI_DATA_SECTION static const Spi_ChannelType SpiJob_1_Flash_ChnlsArray_PB[2] = {SpiConf_SpiChannel_SpiChannel_1,SpiConf_SpiChannel_SpiChannel_2};




/* External device Configuration of Slave_of_Spi3*/
SPI_DATA_SECTION static const Spi_DeviceAttrType Spi_ExternalDeviceConfig_Slave_of_Spi3 =
{
            /* Slave_of_Spi3 */
            SPI_SPURIOUS_CORE_ID_U32,
            (uint32)(FCSPI_TRCTRL_CPOL_HIGH_U32 |     /* Clock Polarity (Idle State) */
            FCSPI_TRCTRL_CPHA_TRAILING_U32 |         /* Clock Phase */
            FCSPI_TRCTRL_PRESCALE_1_U32 |            /* Baudrate: Should=500000.0, Is=500000, Error=0.0% */
            FCSPI_TRCTRL_BYSW_DIS_U32  |             /* Byte Swap Enable or Disable */
            (uint32)(FCSPI_TRCTRL_PCS0_EN_U32 |      /* Chip Select Pin Via Peripheral Engine*/
                    FCSPI_TRCTRL_CONT_EN_U32)        /* Enable continuous chip select */
            ) & FCSPI_TRCTRL_RWBITS_MASK_U32,

            ( ((uint32)(11) << 24u) |                 /* TimeClk2Cs: Should=1000ns, Is=1000, Error=0.0% */
            ((uint32)(11) << 16u) |                   /* TimeCs2Clk: Should=1000ns, Is=1000, Error=0.0% */
            ((uint32)(11) << 8u) |                    /* TimeCs2Cs: Should=1000ns, Is=1000, Error=0.0% */
            ((uint32)(22))
            ),

            /* CFG1 register configuration */
            (uint32)0u                              /* Chip select polarity */
            | FCSPI_CFG1_PINCFG_SIN_INPUT_SOUT_OUTPUT_U32 | FCSPI_CFG1_MATCFG_DIS_U32 
            | FCSPI_CFG1_MASTER_EN_U32
};

/* External device Configuration of SPI_Flash_GD25Q32*/
SPI_DATA_SECTION static const Spi_DeviceAttrType Spi_ExternalDeviceConfig_SPI_Flash_GD25Q32 =
{
            /* SPI_Flash_GD25Q32 */
            SPI_SPURIOUS_CORE_ID_U32,
            (uint32)(FCSPI_TRCTRL_CPOL_LOW_U32 |     /* Clock Polarity (Idle State) */
            FCSPI_TRCTRL_CPHA_TRAILING_U32 |         /* Clock Phase */
            FCSPI_TRCTRL_PRESCALE_1_U32 |            /* Baudrate: Should=100000.0, Is=100000, Error=0.0% */
            FCSPI_TRCTRL_BYSW_DIS_U32  |             /* Byte Swap Enable or Disable */
            (uint32)(FCSPI_TRCTRL_PCS0_EN_U32 |      /* Chip Select Pin Via Peripheral Engine*/
                    FCSPI_TRCTRL_CONT_EN_U32)        /* Enable continuous chip select */
            ) & FCSPI_TRCTRL_RWBITS_MASK_U32,

            ( ((uint32)(35) << 24u) |                 /* TimeClk2Cs: Should=3000ns, Is=3000, Error=0.0% */
            ((uint32)(35) << 16u) |                   /* TimeCs2Clk: Should=3000ns, Is=3000, Error=0.0% */
            ((uint32)(35) << 8u) |                    /* TimeCs2Cs: Should=3000ns, Is=3000, Error=0.0% */
            ((uint32)(118))
            ),

            /* CFG1 register configuration */
            (uint32)0u                              /* Chip select polarity */
            | FCSPI_CFG1_PINCFG_SIN_INPUT_SOUT_OUTPUT_U32 | FCSPI_CFG1_MATCFG_DIS_U32 
            | FCSPI_CFG1_MASTER_EN_U32
};

/* Spi_apExternalDeviceConfigList External device Configuration of Spi*/
SPI_DATA_SECTION static const Spi_ExDevicesAttrsType Spi_aExternalDeviceConfigList[2U] =
{
    /* Slave_of_Spi3 */
    {
        &Spi_ExternalDeviceConfig_Slave_of_Spi3
    },

    /* SPI_Flash_GD25Q32 */
    {
        &Spi_ExternalDeviceConfig_SPI_Flash_GD25Q32
    }
};





/* Job Configuration of SpiJob_0*/
SPI_DATA_SECTION static const Spi_JobCfgType Spi_JobConfig_SpiJob_0 =
{
    /* SpiJob_0 */
    (Spi_ChannelType)1u,
    SpiJob_0_ChnlsArray_PB,                                            /* List of Channels */
    NULL_PTR,                                                        /* job end notify callback */
    NULL_PTR,                                                        /* Start Notification */
    (sint8)0,                                                        /* Priority */
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aJobStats[0],                            /* JobState instance */
    CSIB0,                                                          /* Virtual FCSPI Hardware Module index */
    FCSPI_3_OFFSET,                                                 /* FCSpi device HW unit offset */
    /* External Device Settings */
    SPI_Slave_of_Spi3,                                        /* External Device */
    &Spi_aExternalDeviceConfigList[SPI_Slave_of_Spi3]      /* pcExternalDeviceConfig - pointer to the external device configuration */
#if (SPI_SUP_CONT_EN_SECOND_EDGE_SAMPLE == STD_OFF)
    ,FALSE                   /* If this job is CONT = 1 and SCK_PHA = 1 */
#endif
};

/* Job Configuration of SpiJob_1_Flash*/
SPI_DATA_SECTION static const Spi_JobCfgType Spi_JobConfig_SpiJob_1_Flash =
{
    /* SpiJob_1_Flash */
    (Spi_ChannelType)2u,
    SpiJob_1_Flash_ChnlsArray_PB,                                            /* List of Channels */
    NULL_PTR,                                                        /* job end notify callback */
    NULL_PTR,                                                        /* Start Notification */
    (sint8)0,                                                        /* Priority */
    SPI_SPURIOUS_CORE_ID_U32,
    &g_SPI_tChnJobSeqHwState.aJobStats[1],                            /* JobState instance */
    CSIB1,                                                          /* Virtual FCSPI Hardware Module index */
    FCSPI_2_OFFSET,                                                 /* FCSpi device HW unit offset */
    /* External Device Settings */
    SPI_SPI_Flash_GD25Q32,                                        /* External Device */
    &Spi_aExternalDeviceConfigList[SPI_SPI_Flash_GD25Q32]      /* pcExternalDeviceConfig - pointer to the external device configuration */
#if (SPI_SUP_CONT_EN_SECOND_EDGE_SAMPLE == STD_OFF)
    ,FALSE                   /* If this job is CONT = 1 and SCK_PHA = 1 */
#endif
};

/* Spi_apJobConfigList Job Configuration of Spi*/
SPI_DATA_SECTION static const Spi_JobsCfgType Spi_aJobConfigList[2] =
{
    /* SpiJob_0 */
    {
        &Spi_JobConfig_SpiJob_0
    },

    /* SpiJob_1_Flash */
    {
        &Spi_JobConfig_SpiJob_1_Flash
    }
};



/* Job to Sequence Assignment */
SPI_DATA_SECTION static const Spi_JobType SpiSequence_0_JobsArray_PB[1] = {SpiConf_SpiJob_SpiJob_0};
SPI_DATA_SECTION static const Spi_JobType SpiSequence_1_Flash_SPI2_JobsArray_PB[1] = {SpiConf_SpiJob_SpiJob_1_Flash};




/* Sequence Configuration of SpiSequence_0 */
SPI_DATA_SECTION static const Spi_SeqCfgType Spi_SequenceConfig_SpiSequence_0 =
{
    /* SpiSequence_0 */
    (Spi_JobType)1u,
    SPI_SPURIOUS_CORE_ID_U32,
    SpiSequence_0_JobsArray_PB,                     /* the jobs array of a sequence */
    NULL_PTR,                          /* sequence end notify callack */
    (uint8)FALSE                     /* Interruptible */
};

/* Sequence Configuration of SpiSequence_1_Flash_SPI2 */
SPI_DATA_SECTION static const Spi_SeqCfgType Spi_SequenceConfig_SpiSequence_1_Flash_SPI2 =
{
    /* SpiSequence_1_Flash_SPI2 */
    (Spi_JobType)1u,
    SPI_SPURIOUS_CORE_ID_U32,
    SpiSequence_1_Flash_SPI2_JobsArray_PB,                     /* the jobs array of a sequence */
    NULL_PTR,                          /* sequence end notify callack */
    (uint8)FALSE                     /* Interruptible */
};

/* Spi_apSequenceConfigList Sequence Configuration of Spi*/
SPI_DATA_SECTION static const Spi_SeqsCfgType Spi_aSequenceConfigList[2] =
{
    /* SpiSequence_0 */
    {
        &Spi_SequenceConfig_SpiSequence_0
    },

    /* SpiSequence_1_Flash_SPI2 */
    {
        &Spi_SequenceConfig_SpiSequence_1_Flash_SPI2
    }
};





/* FCSpiChannelAttributesConfig_PB Channel Attribute Configuration of SpiChannel_0*/
SPI_DATA_SECTION static const Spi_ChnlAttrsType Spi_ChnlAttrsConfig_SpiChannel_0 =
{
    SPI_SPURIOUS_CORE_ID_U32,
    (uint32)(FCSPI_TRCTRL_MSB_U32 | FCSPI_TRCTRL_WIDTH_1_U32 | ((uint32)(15))),            /* Channel attribution on TCR register */
    (uint32)(((uint32)(0) << 16) | ((uint32)(3))),                                        /* FIFO Watermark */
    SPI_DATA_RW_16_BITS_PER_UNIT                                                         /* u8DataWidth */
};

/* FCSpiChannelAttributesConfig_PB Channel Attribute Configuration of SpiChannel_1*/
SPI_DATA_SECTION static const Spi_ChnlAttrsType Spi_ChnlAttrsConfig_SpiChannel_1 =
{
    SPI_SPURIOUS_CORE_ID_U32,
    (uint32)(FCSPI_TRCTRL_MSB_U32 | FCSPI_TRCTRL_WIDTH_1_U32 | ((uint32)(7))),            /* Channel attribution on TCR register */
    (uint32)(((uint32)(0) << 16) | ((uint32)(3))),                                        /* FIFO Watermark */
    SPI_DATA_RW_8_BITS_PER_UNIT                                                          /* u8DataWidth */
};

/* FCSpiChannelAttributesConfig_PB Channel Attribute Configuration of SpiChannel_2*/
SPI_DATA_SECTION static const Spi_ChnlAttrsType Spi_ChnlAttrsConfig_SpiChannel_2 =
{
    SPI_SPURIOUS_CORE_ID_U32,
    (uint32)(FCSPI_TRCTRL_MSB_U32 | FCSPI_TRCTRL_WIDTH_1_U32 | ((uint32)(7))),            /* Channel attribution on TCR register */
    (uint32)(((uint32)(0) << 16) | ((uint32)(3))),                                        /* FIFO Watermark */
    SPI_DATA_RW_8_BITS_PER_UNIT                                                          /* u8DataWidth */
};

/* Spi_aChnlAttrsConfigList_ Job Configuration of Spi*/
SPI_DATA_SECTION static const Spi_ChannelsAttrsType Spi_aChnlAttrsConfigList[3] =
{
    /* SpiChannel_0 */
    {
        &Spi_ChnlAttrsConfig_SpiChannel_0
    },

    /* SpiChannel_1 */
    {
        &Spi_ChnlAttrsConfig_SpiChannel_1
    },

    /* SpiChannel_2 */
    {
        &Spi_ChnlAttrsConfig_SpiChannel_2
    }
};




/* Array of FCSpi Unit configurations SpiHwUnit_0_FIFO_Async */
SPI_DATA_SECTION static const Spi_HwUnitCfgType Spi_HwUnitConfig_SpiHwUnit_0_FIFO_Async =
{
    FCSPI_3_OFFSET,
    SPI_SPURIOUS_CORE_ID_U32,                   /* SpiCoreUse */
    SPI_MASTER,
    SPI_HW_UNIT_ASYNC_U8
#if ((SPI_ASYNC_DRIVER == STD_ON) && (SPI_DMA_USED == STD_ON))
    ,FALSE
    ,0u
    ,0u
    ,DMA_INSTANCE_MAX
#endif
};

/* Array of FCSpi Unit configurations SpiHwUnit_1_Sync */
SPI_DATA_SECTION static const Spi_HwUnitCfgType Spi_HwUnitConfig_SpiHwUnit_1_Sync =
{
    FCSPI_2_OFFSET,
    SPI_SPURIOUS_CORE_ID_U32,                   /* SpiCoreUse */
    SPI_MASTER,
    SPI_HW_UNIT_SYNC_U8
#if ((SPI_ASYNC_DRIVER == STD_ON) && (SPI_DMA_USED == STD_ON))
    ,FALSE
    ,0u
    ,0u
    ,DMA_INSTANCE_MAX
#endif
};

/* Array of Hardware Unit configurations */
SPI_DATA_SECTION static const Spi_HwUnitsConfigType Spi_aHwUnitConfigList[2U] =
{
    /* SpiHwUnit_0_FIFO_Async */
    {
    &Spi_HwUnitConfig_SpiHwUnit_0_FIFO_Async
    },

    /* SpiHwUnit_1_Sync */
    {
    &Spi_HwUnitConfig_SpiHwUnit_1_Sync
    }
};


/*==================================================================================================
*                                      GLOBAL CONSTANTS
==================================================================================================*/



/* @violates @ref Spi_PBcfg_c_REF_4 MISRA 2004 Required Rule 8.10, external linkage ... */
/* MODULE-CONFIGURATION Configuration */
SPI_DATA_SECTION const Spi_ConfigType Spi_Config=
{
    2u,                                  /* Number of external devices */
    2u,                                  /* Number of channels */
    1u,                                  /* Number of jobs */
    1u,                                  /* Number of sequences */
    SPI_SPURIOUS_CORE_ID_U32,                                   /* SpiCoreUse */
    Spi_aChannelConfigList,              /* pcChannelConfig */
    Spi_aJobConfigList,                  /* pcJobConfig */
    Spi_aSequenceConfigList,             /* pcSequenceConfig */
    Spi_aChnlAttrsConfigList,            /* pcChannelsAttrConfig */
    Spi_aExternalDeviceConfigList,       /* pcExternalDeviceConfig */
    Spi_aHwUnitConfigList                /* pcHWUnitConfig */
    /**
    * @brief   DEM error parameters
    */
#if (SPI_DEM_ENABLE == STD_ON)
    ,{ (uint32)STD_OFF, (uint32)0U} /* SPI_E_HARDWARE_ERROR parameters*/
    ,{ (uint32)STD_OFF, (uint32)0U} /* SPI_E_TIMEOUT_ERROR parameters*/
#endif /* SPI_DEM_ENABLE == STD_ON */
};



#define SPI_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "Spi_MemMap.h"

#ifdef __cplusplus
}
#endif

/** @} */

